### ISSUE TITLE
请问怎样能替换侧边栏的背景色？

### ISSUE THREAD

**Issue by ruijun** [iissnan/hexo-theme-next#1026]
选用了`Mist`，侧边栏默认是深灰色的，怎样能替换背景色呢？或者说背景可以替换成图片嘛？

**Comment by xovel** [comment]
`..\source\css\_common\components\sidebar`

第一段代码：
```css
.sidebar {
  position: fixed;
  right: 0;
  top: 0;
  bottom: 0;

  width: 0;
  z-index: $zindex-4;
  box-shadow: inset 0 2px 6px black;
  background: $black-deep;
  -webkit-transform: translateZ(0); // http://stackoverflow.com/questions/17079857/position-fixed-broken-in-chrome-with-flash-behind

  a {
    color: $grey-dark;
    border-bottom-color: $black-light;
    &:hover { color: $gainsboro; }
  }

  +tablet() {
    display: none !important;
  }
  +mobile() {
    display: none !important;
  }
}
```
