### ISSUE TITLE
关于代码块的行号建议

### ISSUE THREAD

**Issue by Smalldy** [iissnan/hexo-theme-next#1049]
不知是否有这样的选项可以**取消行号显示**, 当然显示行号其实也没有什么问题,关键是选中代码的时候行号也会被选中,有两个解决方案.一个是取消行号显示,另一个是增加copy按钮,这是一个建议

**Comment by wuxubj** [comment]
你好，选中代码的时候行可以不选中行号，从代码部分开始选择即可，如图：

![001](http://o9w8f1xrl.bkt.clouddn.com/images/others/001.jpg)

我使用的是NexT v5.0.1

**Comment by springjk** [comment]
@Smalldy 在 `themes/next/source/css/_custom/custom.styl` 中添加：
```css
.highlight .gutter{
  display: none;
}
```
