### ISSUE TITLE
headings字体 错误显示

### ISSUE THREAD

**Issue by Captain-Alan** [iissnan/hexo-theme-next#1072]
### Expected behavior (预期行为)
font 已经设为了：
```yaml
  global:  
    external: true  
    family: Lato  
  headings:  
    external: true  
    family: Open Sans  
  posts:  
    external: true  
    family: Roboto  
  logo:  
    external: true  
    family: Great Vibes  
    size: 24  
  codes:  
    external: true  
    family:  
```

headings 本应该显示为 Open Sans
### Actual behavior (实际行为)
h1, h2, ... 均显示为 Georgia,sans

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  ✔Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  - ✔ Pisces
