### ISSUE TITLE
在主页时能否只显示文章的部分内容，不显示全部内容

### ISSUE THREAD

**Issue by pikacode** [iissnan/hexo-theme-next#1088]
### Expected behavior (预期行为)
在主页时能否只显示文章的部分内容，不显示全部内容

NexT Version:
  -  Master

NexT Scheme:
  -  Mist

**Comment by ivan-nginx** [comment]
```
# Automatically Excerpt. Not recommand.
# Please use <!-- more --> in the post to control excerpt accurately.
auto_excerpt:
  enable: false
  length: 150
```
