### ISSUE TITLE
关于多个音乐叠加的处理办法。

### ISSUE THREAD

**Issue by Neveryu** [iissnan/hexo-theme-next#1119]
### Other Informations (Like Browser, System, Screenshots)

https://neveryu.github.io/guestbook/

High一下的这个功能可以一直点击，几首歌一起播放好乱，
如何调整只能放一次歌曲啊
而且放歌的时候怎么停下来 啊？

**Comment by xovel** [comment]
```css
img{ display: block; }
```
