### ISSUE TITLE
/vendors/jquery/index.js?v=2.1.3等资源 加载太慢

### ISSUE THREAD

**Issue by sanyucz** [iissnan/hexo-theme-next#1171]
/vendors/jquery/index.js?v=2.1.3
/vendors/font-awesome/fonts/fontawesome-webfont.woff2?v=4.4.0
/vendors/font-awesome/css/font-awesome.min.css?v=4.4.0

感觉有时候请求会很慢，看了下时间，这三个文件请求很占时间，请问有比较好的解决办法或者思路吗？

![http://od6bpfkkf.bkt.clouddn.com/next-bug-0.png](http://od6bpfkkf.bkt.clouddn.com/next-bug-0.png)
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:
-  Latest Release

NexT Scheme:
-  Pisces

**Comment by yuanyuanyuan** [comment]
web启用gzip压缩，或者直接将他们放到cdn引用

**Comment by flashlab** [comment]
这两个库都可以定制：
[IcoMoon](https://icomoon.io/)    [jQuery Builder](http://projects.jga.me/jquery-builder/)

**Comment by iissnan** [comment]
你可以使用 cdn 版本，主题配置：

```yml
# Script Vendors.
# Set a CDN address for the vendor you want to customize.
# For example
#    jquery: https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js
# Be aware that you should use the same version as internal ones to avoid potential problems.
# Please use the https protocol of CDN files when you enable https on your site.
vendors:
  # Internal path prefix. Please do not edit it.
  _internal: vendors

  # Internal version: 2.1.3
  jquery:
```
