### ISSUE TITLE
Question: Add ToC to pages

### ISSUE THREAD

**Issue by asclines** [iissnan/hexo-theme-next#1181]
Not an issue but a question:
Currently, I have 

``` yml
# Table Of Contents in the Sidebar
toc:
  enable: true
```

in my `_config.yml` file and ToC is generated for posts. But is there a way to add to a sidebar ToC to a page? As opposed to a post?
