### ISSUE TITLE
我想让右下角的菜单按钮在移动端生效，应该怎么解决？

### ISSUE THREAD

**Issue by ljw-bigtail** [iissnan/hexo-theme-next#1210]
···
@media (min-width: 768px) and (max-width: 991px) {
  .sidebar-toggle {
    display: block;
  }
}
@media (max-width: 767px) {
  .sidebar-toggle {
    display: block;
  }
}
···

能显示了，但是功能没有了，应该怎么解决？谢谢。

**Comment by LEAFERx** [comment]
在next\source\css\_common\components\sidebar\sidebar-toggle.styl中：
```css
.sidebar-toggle {
  ...
  +tablet() {
    display: none;
  }
  +mobile() {
    display: none;
  }
}
```
改为
```css
.sidebar-toggle {
  ...
  +tablet() {
    /*display: none;*/
  }
  +mobile() {
    /*display: none;*/
  }
}
```
即可
在next\source\css\_common\components\back-to-top.styl同样操作
