### ISSUE TITLE
[Feature]如何减少代码的 line-height？

### ISSUE THREAD

**Issue by hcoona** [iissnan/hexo-theme-next#128]
代码的间距拉得太大的，希望默认能够调整 pre>code 的 line-height 为 1.2，应该怎么做呢？

**Comment by iissnan** [comment]
`source/css/_custom/custom.styl` 添加：

```css
.post pre, .post .highlight { line-height: 1.2 }
```
