### ISSUE TITLE
可以自定义多说登录样式吗？

### ISSUE THREAD

**Issue by acbetter** [iissnan/hexo-theme-next#1283]
### Expected behavior (预期行为)
![image](https://cloud.githubusercontent.com/assets/13360124/20657848/1473cda2-b574-11e6-9b79-a84b9b15172a.png)

### Actual behavior (实际行为)
![image](https://cloud.githubusercontent.com/assets/13360124/20657862/28c6a522-b574-11e6-8fa8-ca7eff5afab9.png)

### Steps to reproduce the behavior (重现步骤)
在主题配置文件中加入设置项，可以自定义是否替换多说的 CSS 样式。

_config.yml next
```
# Comment
comment:
    disqus: # enter disqus shortname here
    duoshuo:  # enter duoshuo shortname here
    duoshuo_theme: # options: duoshuo_default, next
    youyan: # enter youyan uid here
```

### NexT Informations

NexT Version:
  -  Master

NexT Scheme:
  -  All schemes
