### ISSUE TITLE
文章标题下的发表时间不见了

### ISSUE THREAD

**Issue by CChenYixin** [iissnan/hexo-theme-next#1300]
原本：
![原来](http://ohqryljkl.bkt.clouddn.com/1.JPG)

不知道删了什么文件后，变成了这样

现在：

![现在](http://ohqryljkl.bkt.clouddn.com/%E6%8D%95%E8%8E%B7.JPG)

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist  ✔
  -  Pisces

右键检查元素，属于“header”部分，class=“post-meta”，但因为无法定位是哪个文件，所以不知道该如何修改。

这样该怎么操作呢？

**Comment by Neveryu** [comment]
git可以查看你删了什么文件，改动了哪些

**Comment by CChenYixin** [comment]
@Neveryu 谢谢你，问题已经解决。不小心删掉了配置文件中的这个部分
```
# Post meta display settings
post_meta:
  created_at: true
  updated_at: false
  categories: true
```
