### ISSUE TITLE
修改字体为 Ubuntu 后 Mist 下 Chrome 会出现标题换行的现象

### ISSUE THREAD

**Issue by Homulilly** [iissnan/hexo-theme-next#1312]
### Steps to reproduce the behavior (重现步骤)
在主题设置中将字体 Lato 修改为 Ubuntu 后，首页的部分标题会出现最后一个字换行的现象。
Firefox 没问题， Chrome 会出现

比如： `Python3 一些中文`
![](https://i.imgur.com/1HEWo3y.png)

NexT Version:
  -  5.1.0 
  -  5.0.1

NexT Scheme:
  -  Mist

### Other Informations (Like Browser, System, Screenshots)
- 系统：Ubuntu 16.04
- 浏览器： Chrome V55

我尝试注释掉了 `[themes]/next/source/css/_common/components/post/post-title.styl` 中 `display: inline-block;` ，可以解决。

```css
.posts-expand .post-title-link {
    display: inline-block;
...
}
```
注释掉这个 css 是否会产生其他影响？
