### ISSUE TITLE
侧边社交栏乱码

### ISSUE THREAD

**Issue by tianxieao** [iissnan/hexo-theme-next#1318]
### Actual behavior (实际行为)
[左下角](https://tianxieao.github.io/)
### Steps to reproduce the behavior (重现步骤)
```
# Social Links
# Key is the link label showing to end users.
# Value is the target link (E.g. GitHub: https://github.com/iissnan)
social:
  #LinkLabel: Link
  GitHub：https://github.com/tianxieao 


# Social Links Icons
# Icon Mapping:
#   Map a menu item to a specific FontAwesome icon name.
#   Key is the name of the item and value is the name of FontAwsome icon. Key is case-senstive.
#   When an globe mask icon presenting up means that the item has no mapping icon.
social_icons:
  enable: true
  # Icon Mappings.
  # KeyMapsToSocalItemKey: NameOfTheIconFromFontAwesome
  GitHub: github
  #Twitter: twitter
  #Weibo: weibo
```
