### ISSUE TITLE
求助：标签跟分类页显示不正常

### ISSUE THREAD

**Issue by tianxieao** [iissnan/hexo-theme-next#1323]
### Expected behavior (预期行为)
标签页
![](http://i1.piimg.com/567571/bc8c976321bf8c35.png)
 分类页
![](http://i1.piimg.com/567571/46615b927dfba826.png)
## Actual behavior (实际行为)
 标签页
![](http://i1.piimg.com/567571/68c1c3b7b9fb48e4.png)
分类页
![](http://i1.piimg.com/567571/adb0c12cd904f89e.png)

### Steps to reproduce the behavior (重现步骤)
主题菜单栏配置
```
menu:
  home: /
  # categories: /categories
  about: /about
  #archives: /archives
  #tags: /tags
  #sitemap: /sitemap.xml
  #commonweal: /404.html
```

### NexT Informations
`5.1.0`
Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces
