### ISSUE TITLE
[feature request] 自定义隐藏某些页面的publish date

### ISSUE THREAD

**Issue by cogitoxin** [iissnan/hexo-theme-next#1331]
可不可以像comment=false一样，设定date=false之后就能隐藏publish date呢？

**Comment by ivan-nginx** [comment]
In `_config.yml` u can change this:
```
# Post meta display settings
post_meta:
  item_text: false
  created_at: true
  updated_at: true
  categories: true
```
