### ISSUE TITLE
像主标题、副标题、作者，这些内容支持国际化吗？

### ISSUE THREAD

**Issue by topcss** [iissnan/hexo-theme-next#1378]
### Expected behavior (预期行为)
如题，如果可以如何设置？

**Comment by topcss** [comment]
切换不同的语言，网站的主题都在变。期望主标题这些内容也随着文章的内容，变成对应的语言的文字。即：可以配置不同文字的主标题、副标题...。
![folding](https://cloud.githubusercontent.com/assets/2252451/22049322/7b52a504-dd6d-11e6-9a8e-ae8bdb87e075.gif)

**Comment by Neveryu** [comment]
那这个你可能需要修改 next 主题下的language文件下的语言包的配置文件。
比如说：
```
menu:
  home: /
  archives: /archives
  categories: /categories
  # tags: /tags
  guestbook: /guestbook
about: /about
```
那么，在中文语言包下，你就需要：
```
menu:
  home: 首页
  archives: 归档
  categories: 分类
  tags: 标签
  guestbook: 留言
  about: 关于
  search: 搜索
commonweal: 公益404
```
同理，在其他语言包下，也需要提供对应语言的翻译，大概有十几种语言包吧。
那么呢，这个主标题和副标题，都是由个人自己取的名字，所以，next 主题是无法做到帮大家提供对应语言的翻译的。
那么，这个就需要自己动手修改 language下的内容，增加自己需要的语言
