### ISSUE TITLE
新版本部署不成功

### ISSUE THREAD

**Issue by varzy** [iissnan/hexo-theme-next#1443]
2017.02.18 我重新 clone 了贵项目，发现部署不成功。运行 hexo s 出现下列结果：

```
    at Promise._settlePromiseFromHandler (D:\CodeHub\_Blog\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (D:\CodeHub\_Blog\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (D:\CodeHub\_Blog\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (D:\CodeHub\_Blog\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (D:\CodeHub\_Blog\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (D:\CodeHub\_Blog\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (D:\CodeHub\_Blog\node_modules\bluebird\js\release\async.js:17:14)
```

发现是 zh-Hans.yml 文件中多写了一个 `  schedule: 日程`：

```
menu:
  home: 首页
  archives: 归档
  categories: 分类
  schedule: 日程
  tags: 标签
  about: 关于
  search: 搜索
  schedule: 日程
  sitemap: 站点地图
  commonweal: 公益404
```

去掉后即恢复正常。望修复。
