### ISSUE TITLE
请问如何更改小代码标签即为 ` ` 之间字的颜色和背景颜色，例如您现在的颜色就是灰色，急求，谢谢啦

### ISSUE THREAD

**Issue by Dingxuewen** [iissnan/hexo-theme-next#1475]
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by Neveryu** [comment]
[https://neveryu.github.io/2017/01/18/html5shiv/](https://neveryu.github.io/2017/01/18/html5shiv/)

**Comment by Neveryu** [comment]
``` css
//修改文章内code样式
code {color:#fff;background:#333;}
```
