### ISSUE TITLE
请问怎么在侧边栏社交处添加邮箱呢

### ISSUE THREAD

**Issue by tunsuy** [iissnan/hexo-theme-next#1489]
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by iissnan** [comment]
You can use the `mailto:` URL scheme for the link, but it is danger to do that cause there are tons of spam.

```yml
social:
  Email: mailto:for-spam@gmail.com

social_icons:
  enable: true
  Email: envelope
```
