### ISSUE TITLE
关闭多说，启用 Disqus 失败

### ISSUE THREAD

**Issue by iTofu** [iissnan/hexo-theme-next#1527]
### Expected behavior (预期行为)

多说挂了，打算关闭多说评论系统，启用 Qisqus 评论系统。

### Actual behavior (实际行为)

1. 并未启用成功，`hexo s` or `hexo d` 后依然显示的是多说，查看：https://note.leodev.me 。

2. 另外 Guidelines for Contributing 页面的 F.A.Q 链接挂了（DNS problem）：
  https://github.com/iissnan/hexo-theme-next/blob/master/.github/CONTRIBUTING.md

### Steps to reproduce the behavior (重现步骤)

1. Theme _config.yml:
  
  ```yml
  # Duoshuo ShortName
  # duoshuo_shortname: leodev
  
  # Disqus
  disqus_shortname: leodev
  
  # Share
  duoshuo_share: false
  
  # Make duoshuo show UA
  # user_id must NOT be null when admin_enable is true!
  # you can visit http://dev.duoshuo.com get duoshuo user id.
  # duoshuo_info:
  #   ua_enable: false
  #   admin_enable: false
  #   user_id: xxx
  #   admin_nickname: xx
  #   data_author_key: 1
  ```

2. Terminal:

  ```bash
  hexo clean
  hexo s # preview
  hexo g # general
  hexo d # deploy
  ```

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release  ✔ 
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces  ✔ 

### Other Informations (Like Browser, System, Screenshots)

* macOS 10.12.3
* Chrome 57.0.2987.98

**Comment by iissnan** [comment]
Remove `duoshuo_shortname` from your theme configuration file and the newest commit in master branch now require disqus setting to be:

```yml
disqus:
  enable: true
  shortname: 
  count: true
```
