### ISSUE TITLE
RSS in Menubar (Image?)

### ISSUE THREAD

**Issue by jacksgt** [iissnan/hexo-theme-next#153]
This themes (by default) puts the RSS in the sidebar.
I wanted to have a link to the RSS feed in the menubar. A few little changes made this possible:
```
diff --git a/_config.yml b/_config.yml
index 6a20238..97e53b8 100755
--- a/_config.yml
+++ b/_config.yml
@@ -5,6 +5,7 @@ menu:
   archives: /archives
   tags: /tags
   #commonweal: /404.html
+  rss: /atom.xml

 # Place your favicon.ico to /source directory.
 favicon: /favicon.ico
diff --git a/languages/default.yml b/languages/default.yml
index fce8509..d8ce719 100644
--- a/languages/default.yml
+++ b/languages/default.yml
@@ -9,6 +9,7 @@ menu:
   categories: Categories
   tags: Tags
   about: About
+  rss: RSS

 sidebar:
   overview: Overview
```
Result: http://upper.cf/ul/rss-patch-hexo.png

Unfortunately, I do not know how to display an image above the text (e.g. http://upper.cf/ul/rss-iconbw.gif)
Any hints?

**Comment by iissnan** [comment]
One more step: add a css class named `icon-rss` and specify the rules for this class. For example:

```css
.icon-rss {
    background: url(http://upper.cf/ul/rss-iconbw.gif) no-repeat;
    /* other rules */
}
```

Actually, NexT has built-in icons for rss, but the class name is `icon-feed`. So another option is to change your menu setting for rss to:

```yml
about: About
feed: /atom.xml
```

**Comment by jacksgt** [comment]
Ok, thank you.
So you only need to add the following things to get an RSS icon in the Menubar:
```yml
# theme's _config.yml
menu:
   feed: /atom.xml

# theme's language file
# (e.g. next/languages/default.yml)
menu:
   feed: RSS
```
Thanks again for your support!
