### ISSUE TITLE
目录自动生成的序号在哪里去除呢？给人很杂乱的感觉

### ISSUE THREAD

**Issue by op134972** [iissnan/hexo-theme-next#1553]

**Comment by jetyu** [comment]
以前貌似没这个问题

**Comment by skyue** [comment]
主题配置文件下有个`toc`选项，将其下的`number`设置为`false`应该就行了。

```
# Table Of Contents in the Sidebar
toc:
  enable: true

  # Automatically add list number to toc.
  number: false
```
