### ISSUE TITLE
如何修改首页文章摘要的显示方式？

### ISSUE THREAD

**Issue by zproo** [iissnan/hexo-theme-next#1557]
**问题：** 让博客首页的文章**摘要部分**只显示无样式的纯文本（现在带有标题或段落的css样式）应该如
何实现？
**达到效果：** 在网上看到的博客，但是作者并没有博客代码仓库。。。
[示例博客](http://www.vat58.com/)

以前没有接触过swig模板语言，想请教一下各位如何实现我要的效果。。

---
**显示效果对比：**

![pic1](https://raw.githubusercontent.com/zproo/doc-library/master/1.png)
---
**代码对比：**

![pic2](https://raw.githubusercontent.com/zproo/doc-library/master/22.png)

**Comment by skyue** [comment]
不用改代码那么复杂吧，主题配置文件中的自动摘要就是不带样式的纯文本：

```
# Automatically Excerpt. Not recommend.
# Please use <!-- more --> in the post to control excerpt accurately.
auto_excerpt:
  enable: true
  length: 200
```

`enable`设置为`true`，`length`控制自动摘要的字数。
