### ISSUE TITLE
Hexo 换行问题

### ISSUE THREAD

**Issue by payne4handsome** [iissnan/hexo-theme-next#1672]
### Expected behavior (预期行为)
在文本编辑器中回车，在页面上不换行
### Actual behavior (实际行为)
在文本编辑器中回车，在页面上换行了，安装markdown的语法应该是  
两个空格加回车才是换行呀

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by SysFlat** [comment]
我也很纠结这个换行的问题，如果自己换行的话网页排版出来实在是丑的可以。。。。现在我只能一行写好长好长才能换个行好烦

**Comment by michaelHL** [comment]
与NexT主题无关, Hexo利用自带的解析器对md源文件进行解析. 也许可行的解决方案:
1. 安装 [hexo-renderer-marked](https://github.com/hexojs/hexo-renderer-marked)
   ```sh
   npm install hexo-renderer-marked --save
   ```
   不过最新的Hexo貌似已经装上了这个.
2. 在站点配置文件中加上:
   ```yaml
   marked:
     gfm: true
     pedantic: false
     sanitize: false
     tables: true
     breaks: false
     smartLists: true
     smartypants: true
     modifyAnchors: ''
     autolink: true
   ```
   主要将是 `gfm` 以及 `breaks` 的设定. 其他设定的效果如何没有试验,
