### ISSUE TITLE
几个小问题

### ISSUE THREAD

**Issue by jiangxy** [iissnan/hexo-theme-next#17]
一些小问题哈
1. about页面的blockquote元素样式有问题。和post中的不一样。
2. languages/zh-Hans.yml中的“x个日志”似乎改成“x篇日志”更合适。
3. title和author会自动转换为大写，感觉让用户自己选择更好。
4. demo中的title那里是有圆角的，但实际使用中没有。

另外问个问题，文章的宽度是固定的么？如果屏幕分辩率较高，会不会导致文章集中在中间一条？

**Comment by iissnan** [comment]
谢谢。我会修正你提到的问题。

目前文章的宽度是固定的。分辨率较高的情况，我还没有测试过。

**Comment by iissnan** [comment]
前面三个问题已经修正了。

第四个问题，那个圆角是我定制的，我的想法让用户可以在`_custom.styl`定制自己的风格：）。
参见我的定制：[_custom.styl](https://github.com/iissnan/hexo-theme-next/blob/iissnan/source/css/_custom.styl)

**Comment by iissnan** [comment]
我在想把目前`blockquote`的样式做成一个`helper class`，当需要的时候使用。因为这个样式是居中的，对于多行的文本看来有点怪。

默认的`blockquote`样式跟`GitHub`类似，在前面用竖线表示。当需要目前`blockquote`的样式的时候，独立引用，例如：

```
<blockquote class="blockquote-center">blah blah blah</blockquote>
```

**Comment by jiangxy** [comment]
更新真快，赞:+1:
提几个建议：
1. 感觉uppercase不必做成配置项，用户自己输入大写字符就可以了。
2. 赞成blockquote单独引用，确实居中有点怪
3. about页面的图片居中了，是修复blockquote导致的么？我想让一些图片居左应该怎样处理？
4. 我试了下似乎主题的_config.yml会覆盖站点的_config.yml，所以每次`git pull`之后都要清空主题的_config.yml的一些项目。配置项冲突时，能否优先使用站点的_config.yml？

**Comment by iissnan** [comment]
1. :ok: 
2. :ok: 
3. 嗯，把文章里面的样式提到全局去了。下个提交修正。
4. 主题的 `_config.yml` 确实会覆盖站点的 `_config.yml` ，这是 Hexo 的处理逻辑。我建议将一些配置写在站点的`_config.yml`中，这样更新主题会减少一些冲突。

例如我的站点 `_config.yml` 配置：

```
# =============================================================================
# NexT Theme configuration
# =============================================================================

# Duoshuo
duoshuo_shortname: 

# Social links
social:
  github: https://github.com/iissnan
  twitter: https://twitter.com/iissnan
  weibo: http://weibo.com/iissnan
  douban: http://douban.com/people/iissnan
  zhihu: http://www.zhihu.com/people/iissnan

# Google分析ID
google_analytics:


# 百度分析ID
baidu_analytics:

# Creative Commons 4.0 International License.
# http://creativecommons.org/
# Available: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
creative_commons: by-nc-sa

# Specify the date when the site was setup
since: 2011

# =============================================================================
# End NexT Theme configuration
# =============================================================================
```
