### ISSUE TITLE
安装hexo-generator-search插件并添加相关配置后菜单无搜索按钮

### ISSUE THREAD

**Issue by xyz1001** [iissnan/hexo-theme-next#1704]
### Expected behavior (预期行为)

菜单栏出现搜索按钮
### Actual behavior (实际行为)

菜单栏无搜索按钮
### Steps to reproduce the behavior (重现步骤)
执行命令npm install hexo-generator-search --save安装插件
在hexo配置文件_config.yml后面添加
```
search:
  path: search.xml
  field: post
  format: html
  limit: 10000
````
重新部署刷新

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  ✔ -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  ✔-  Mist
  -  Pisces
