### ISSUE TITLE
AlgoliaSearchError: Please provide an API key. Update index fails

### ISSUE THREAD

**Issue by BeethovenVirus** [iissnan/hexo-theme-next#1711]
### Expected behavior (预期行为)
当配置完成，在站点根目录下执行 hexo algolia 来更新 Index 并成功

### Actual behavior (实际行为)
AlgoliaSearchError: Please provide an API key. Usage: algoliasearch(applicationID, apiKey, opts)

### Steps to reproduce the behavior (重现步骤)
I am stricly following the tutorial guide of this link 
http://theme-next.iissnan.com/third-party-services.html#search-system

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master  ✔ 
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces  ✔ 

### Other Information (Like Browser, System, Screenshots)

![image](https://user-images.githubusercontent.com/28602460/27001901-454a5b5e-4e07-11e7-9997-8c8facf3e3ae.png)

- 我确定我按照要求修改了站点配置文件，applicationID 可以顺利找到，然而提示找不到API Key，这是为什么呢？

```
algolia: 
  applicationID: KEBR84**** 
  apiKey: 04efacb********75bda019f
  adminApiKey: fb5e363******d32a7e35 
  indexName: **** 
  chunkSize: 5000 

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next


```
