### ISSUE TITLE
侧边栏设计链接那里中文显示乱码

### ISSUE THREAD

**Issue by Marze1994** [iissnan/hexo-theme-next#1715]
### Actual behavior (实际行为)
```
# Social Links
# Key is the link label showing to end users.
# Value is the target link (E.g. GitHub: https://github.com/iissnan)
social:
  #LinkLabel: Link
  GitHub: https://github.com/Marze1994
  知乎: https://www.zhihu.com/people/zengjie21/activities
  
# Social Links Icons
# Icon Mapping:
#   Map a menu item to a specific FontAwesome icon name.
#   Key is the name of the item and value is the name of FontAwesome icon. Key is case-senstive.
#   When an globe mask icon presenting up means that the item has no mapping icon.

social_icons:
  enable: true
  # Icon Mappings.
  # KeyMapsToSocialItemKey: NameOfTheIconFromFontAwesome
  GitHub: github
  知乎: globe
  Twitter: twitter
  Weibo: weibo

```

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release✔
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces✔

### Other Information (Like Browser, System, Screenshots)
Browse:
 -  谷歌

System:
 -  win10

Screenshots:
![default](https://user-images.githubusercontent.com/25895849/27122432-3d7b4f32-511d-11e7-9a2e-90e562062907.png)
