### ISSUE TITLE
建议把headings和title的字体分开设置

### ISSUE THREAD

**Issue by clouduan** [iissnan/hexo-theme-next#1788]
### Expected behavior 
想把headings的字体改成宋体显示，title的字体仍然用Microsoft Yahei

### Actual behavior 
headings的字体改了，但是title的字体也成了宋体

### NexT Information

_config.yml文件中字体部分的设置信息为
```
 global:
    # external: true will load this font family from host.
    external: true
    family: "Microsoft YaHei"

  # Font settings for Headlines (h1, h2, h3, h4, h5, h6)
  # Fallback to `global` font settings.
  headings:
    external: true
    family: SimSun

  # Font settings for posts
  # Fallback to `global` font settings.
  posts:
    external: true
    family: 

```
#这里只有headings的设置，所以想建议把title和headings的字体分开设置
