### ISSUE TITLE
How to config menu if I'm using relative_link?

### ISSUE THREAD

**Issue by hueyhe** [iissnan/hexo-theme-next#1821]
### I agree and want to create new issue 
Hi, I was using nginx to proxy my blog site to a sub url like `mydomain.com/blog`. Hence I set `relative_link` to `true` and also removed all the leading slashes in my menu config. Since `home` original absolute url is `/`, I just left it blank. My menu config is as below. However, when I tried to navigate to a menu (e.g. categories), the page just refreshed without navigating. How can I set up the menu config correctly if I'm using `relative_link`?

#### My menu config
```yml
# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

# When running the site in a subdirectory (e.g. domain.tld/blog), remove the leading slash (/archives -> archives)
menu:
  home: 
  categories: categories
  #about: /about
  archives: archives
  tags: tags
  # sitemap: /sitemap.xml
  #commonweal: /404.html


# Enable/Disable menu icons.
# Icon Mapping:
#   Map a menu item to a specific FontAwesome icon name.
#   Key is the name of menu item and value is the name of FontAwsome icon. Key is case-senstive.
#   When an question mask icon presenting up means that the item has no mapping icon.
menu_icons:
  enable: true
  #KeyMapsToMenuItemKey: NameOfTheIconFromFontAwesome
  home: home
  about: user
  categories: th
  schedule: calendar
  tags: tags
  archives: calendar
  sitemap: sitemap
  commonweal: heartbeat
```

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
Navigate to menu correctly.

### Actual behavior 
Just refreshing the current page.

### Steps to reproduce the behavior 
1. set `relative_link` to `true` in hexo config
2. remove all the slashes in menu config of NEXT theme
3. hexo clean & regenerate files then start server

### NexT Information

**NexT Version:**

```
[ ] Master
[ ] Latest Release
[x] Old version - 5.1.0
```

**NexT Scheme:**

```
[x] All schemes
[ ] Muse
[ ] Mist
[ ] Pisces
[ ] Gemini
```

**Comment by ivan-nginx** [comment]
Actually, this bug not NexT theme. Your links not worknig, and links generated by Hexo, not by theme.

What in hexo `_config.yml`?  U set root url for your subdirectory?
```yml
# URL
## If your site is put in a **subdirectory**, set url as '**http://yoursite.com/child**' and root as '/child/'
url: 
```

**Comment by hueyhe** [comment]
Here's the url config in my hexo `_config.yml`
```yml
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://mydomain.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
```

I didn't set the root url for a subdirectory. Because in my case, the blog site is served under a specific port like 8888. The blog is accessible via `https://mydomain.com:8888`. I'm using nginx to proxy path `https://mydomain.com/blog` to port 8888. If `relative_link` is set to false, assets url in blog index.html would be like `/css/main.css`, which forced browser to load assets via url `https://mydomain.com/css/main.css`. Apparently `https://mydomain.com/blog/css/main.css` should be the correct url. That's why I'm using relative path but not setting root to a subdirectory.

**Comment by ivan-nginx** [comment]
@hueyhe i understand it.

> which forced browser to load assets via url https://mydomain.com/css/main.css.
> Apparently https://mydomain.com/blog/css/main.css

> If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'

So, if your site in subdirectory, u must set this url for links working.

Nginx — is Nginx. Why u do what root path of hyperlinks generated by Hexo will rewrite something with Nginx? It's not.

Can u show your Nginx configuration?

**Comment by hueyhe** [comment]
Here is my nginx proxy config.
```config
server {
        listen 443 ssl;
        ssl on;

        ...

        location /blog/ {
                proxy_pass http://0.0.0.0:8888/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
        }

        ...
}
```

@ivan-nginx My site is not in subdirectory. It is served in the root directory. It just looks like in a sub directory because of the proxy. Is it possible to simply change the menu link to a relative link to solve this problem? I'm a little bit confused because I didn't see any href link on menu `<a>` tag.

**Comment by ivan-nginx** [comment]
> Is it possible to simply change the menu link to a relative link to solve this problem?

If it was simple to solve, we don't talk here.

Try to understand what i'm say: nginx — it's proxy server, right? He's can't change the configuration and/or generate your hyperlinks what actually do Hexo, right? Nginx just proxies your queries and get static data. So, if your links don't work, trouble in Hexo config files.

> If relative_link is set to false, assets url in blog index.html would be like /css/main.css,

And this is fine because your blog url is set to:
```yml
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
```
Forget about `relative_path` option. There is not need here. Turn it off, you have Nginx for that get all pathes.

1. Try to off `relative_path`. 
2. url: http://yoursite.com/blog
3. /blog/

Try to do this steps.
