### ISSUE TITLE
关于Menu & Sidebar icons #1830

### ISSUE THREAD

**Issue by JiangTJ** [iissnan/hexo-theme-next#1865]
Menu & Sidebar icons #1830 是个挺好的新特性，路径和图标一起设置，但个人认为，采用对象分割会更好些
例如
```yaml
menu:
  home: {path:/,icon:home}
```
或者
```yaml
menu:
  home:
     path:/
     icon:home
```
这样的设计有两点好处

1. 用户知道他们设置的是什么属性
2. 易于扩展，如需扩展菜单定义不同颜色或者部分菜单不可点击（临时性的，但不想隐藏）等情况，可添加不同的属性来标记
