### ISSUE TITLE
Pics in blog cannot display, which says "The requested content cannot be loaded. Please try again later."

### ISSUE THREAD

**Issue by MrMorning** [iissnan/hexo-theme-next#1874]
- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***
## Problem Description
For some blogs i've posted, some of the pics cannot be displayed well, such as [this blog](http://gengchen.tech/2017/08/23/CF736C/), there was just one pic in that page, but it cannot be displayed and said "The requested content cannot be loaded. Please try again later.", 

## Try to solve
First i search a [issue](https://github.com/CodeFalling/hexo-asset-image/issues/4), but it was closed without solution mentioned.

Then i inserted another pic from other source into that page to test, finally, the first pic displayed and another pics didnt display as you can seen in that page.

#### parts of my blog config
```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Konjac's Blog
subtitle: +1s
description: problems, notes and solutions
author: Geng Chen
language: zh-Hans
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://mrmorning.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-next 

//something are skipped

search:
  path: search.xml
  field: post
  format: html
  limit: 10000
# hexo-tag-cloud
tag_cloud:
    textFont: Trebuchet MS, Helvetica
    textColour: \#333
    textHeight: 12
    outlineColour: \#E2E1D1
# Sitemap
sitemap:
  path: sitemap.xml
#aritcle number
index_generator:
  per_page: 5

archive_generator:
  per_page: 20
  yearly: true
  monthly: true

tag_generator:
  per_page: 10

kramed:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true
```

#### package
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.2.2"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-deployer-git": "^0.2.0",
    "hexo-directory-category": "^1.0.3",
    "hexo-encrypt": "^0.2.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-searchdb": "^1.0.3",
    "hexo-generator-sitemap": "^1.1.2",
    "hexo-generator-tag": "^0.2.0",
    "hexo-inject": "^1.0.0",
    "hexo-migrator-rss": "^0.1.2",
    "hexo-migrator-wordpress": "^0.1.2",
    "hexo-neat": "^1.0.4",
    "hexo-renderer-ejs": "^0.2.0",
    "hexo-renderer-mathjax": "^0.6.0",
    "hexo-renderer-pandoc": "^0.1.1",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.2.0",
    "hexo-tag-cloud": "^2.0.7"
  }
}
```

### theme config
```
//something is skipped
# ---------------------------------------------------------------
# Third Party Services Settings
# ---------------------------------------------------------------

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML


# Swiftype Search API Key
#swiftype_key:

# Baidu Analytics ID
#baidu_analytics:

# Duoshuo ShortName
#duoshuo_shortname:

# Disqus
disqus:
  enable: false
  shortname: konjac
  count: false

# Hypercomments
#hypercomments_id:

# Gentie productKey
#gentie_productKey:7c3e703b657a43d6bf26bf12f5686b27

# changyan
changyan:
  enable: false
  appid:
  appkey:

# Support for youyan comments system.
# You can get your uid from http://www.uyan.cc
#youyan_uid: your uid

# Support for LiveRe comments system.
# You can get your uid from https://livere.com/insight/myCode (General web site)
livere_uid: MTAyMC8yNzk0Ni80NTIz

# Baidu Share
# Available value:
#    button | slide
# Warning: Baidu Share does not support https.
#baidushare:
##  type: button

# Share
#jiathis:
# Warning: JiaThis does not support https.
#add_this_id:

# Share
#duoshuo_share: true

# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
#google_site_verification:

# Google Analytics
#google_analytics:

# Yandex Webmaster tools verification setting
# See: https://webmaster.yandex.ru/
#yandex_site_verification:

# CNZZ count
#cnzz_siteid:

# Application Insights
# See https://azure.microsoft.com/en-us/services/application-insights/
# application_insights:

# Make duoshuo show UA
# user_id must NOT be null when admin_enable is true!
# you can visit http://dev.duoshuo.com get duoshuo user id.
duoshuo_info:
  ua_enable: true
  admin_enable: false
  user_id: 0
  #admin_nickname: Author


# Facebook SDK Support.
# https://github.com/iissnan/hexo-theme-next/pull/410
facebook_sdk:
  enable: false
  app_id:       #<app_id>
  fb_admin:     #<user_id>
  like_button:  #true
  webmaster:    #true

# Facebook comments plugin
# This plugin depends on Facebook SDK.
# If facebook_sdk.enable is false, Facebook comments plugin is unavailable.
facebook_comments_plugin:
  enable: false
  num_of_posts: 10  # min posts num is 1
  width: 100%       # default width is 550px
  scheme: light     # default scheme is light (light or dark)

# VKontakte API Support.
# To get your AppID visit https://vk.com/editapp?act=create
vkontakte_api:
  enable: false
  app_id:       #<app_id>
  like:         true
  comments:     true
  num_of_posts: 10


# Show number of visitors to each article.
# You can visit https://leancloud.cn get AppID and AppKey.
leancloud_visitors:
  enable: false
  app_id: #<app_id>
  app_key: #<app_key>

# Show PV/UV of the website/page with busuanzi.
# Get more information on http://ibruce.info/2015/04/04/busuanzi/
busuanzi_count:
  # count values only if the other configs are false
  enable: false
  # custom uv span for the whole site
  site_uv: true
  site_uv_header: <i class="fa fa-user"></i>
  site_uv_footer:
  # custom pv span for the whole site
  site_pv: true
  site_pv_header: <i class="fa fa-eye"></i>
  site_pv_footer:
  # custom pv span for one page only
  page_pv: true
  page_pv_header: <i class="fa fa-file-o"></i>
  page_pv_footer:


# Tencent analytics ID
# tencent_analytics:

# Tencent MTA ID
# tencent_mta:


# Enable baidu push so that the blog will push the url to baidu automatically which is very helpful for SEO
baidu_push: false

# Google Calendar
# Share your recent schedule to others via calendar page
#
# API Documentation:
# https://developers.google.com/google-apps/calendar/v3/reference/events/list
calendar:
  enable: false
  calendar_id: <required>
  api_key: <required>
  orderBy: startTime
  offsetMax: 24
  offsetMin: 4
  timeZone:
  showDeleted: false
  singleEvents: true
  maxResults: 250

# Algolia Search
algolia_search:
  enable: false
  hits:
    per_page: 10
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}"
    hits_stats: "${hits} results found in ${time} ms"


# Local search
local_search:
  enable: true

# External URL with BASE64 encrypt & decrypt
# Usage: {% exturl text url "title" %}
# Alias: {% extlink text url "title" %}
exturl: false


#! ---------------------------------------------------------------
#! DO NOT EDIT THE FOLLOWING SETTINGS
#! UNLESS YOU KNOW WHAT YOU ARE DOING
#! ---------------------------------------------------------------

# Motion
use_motion: true

# Fancybox
fancybox: true

# Canvas-nest
canvas_nest: false

#three_waves
three_waves: false

# Script Vendors.
# Set a CDN address for the vendor you want to customize.
# For example
#    jquery: https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js
# Be aware that you should use the same version as internal ones to avoid potential problems.
# Please use the https protocol of CDN files when you enable https on your site.
vendors:
  # Internal path prefix. Please do not edit it.
  _internal: lib

  # Internal version: 2.1.3
  jquery:

  # Internal version: 2.1.5
  # See: http://fancyapps.com/fancybox/
  fancybox:
  fancybox_css:

  # Internal version: 1.0.6
  # See: https://github.com/ftlabs/fastclick
  fastclick:

  # Internal version: 1.9.7
  # See: https://github.com/tuupola/jquery_lazyload
  lazyload:

  # Internal version: 1.2.1
  # See: http://VelocityJS.org
  velocity:

  # Internal version: 1.2.1
  # See: http://VelocityJS.org
  velocity_ui:

  # Internal version: 0.7.9
  # See: https://faisalman.github.io/ua-parser-js/
  ua_parser:

  # Internal version: 4.6.2
  # See: http://fontawesome.io/
  fontawesome:

  # Internal version: 1
  # https://www.algolia.com
  algolia_instant_js:
  algolia_instant_css:

  # Internal version: 1.0.0
  # https://github.com/hustcc/canvas-nest.js
  canvas_nest:
  
  #three
  three:
  three_waves:



# Assets
css: css
js: js
images: images

# Theme version
version: 5.1.0
special_effects:
  collapse_code: 0
```

#### Generate information
```
(node:16874) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
INFO  [hexo-inject] installing hotfix for hexojs/hexo#1791
INFO  Start processing
WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

INFO  [CF838B]Diverging Directions - 线段树维护子树 encryped
WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

INFO  SDOI2017 Round 1爆零记+阶段性总结 encryped
WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

WARN  the qiniu ak or sk is incorrect, please check you _config.yml.
maybe you want this:
encrypt:
	qiniu_ak: your access key of qiniu
	qiniu_sk: your secret key of qiniu

INFO  copy crypto-js.js to public/js/
INFO  Files loaded in 24 s
```
