### ISSUE TITLE
Mist开启问题

### ISSUE THREAD

**Issue by kdplus** [iissnan/hexo-theme-next#189]
* 去掉了主题配置文件中的scheme: Mist前的#。但是并没有开启Mist主题。不知道是我哪里操作的问题。

**Comment by mingmings** [comment]
站点 config 里写上 theme： next ，主题 config 里，取消 Mist 的注释试试

**Comment by iissnan** [comment]
这个姿势是对的。你的操作步骤是？

**Comment by kdplus** [comment]
@mingmings 正是这么操作的T-T

**Comment by kdplus** [comment]
@iissnan 姿势就是在\themes\next\_config.yml去掉了scheme: Mist前面的#。不行之后，直接把主页readme里面的那个份完全复制了一份在我的config里面（因为似乎有些不一样）。结果还是不行

**Comment by iissnan** [comment]
hm... 有点奇怪。

试试 `hexo clean` 下

**Comment by kdplus** [comment]
@iissnan 是啊感觉很奇怪。我把config贴出来看看？

**Comment by iissnan** [comment]
嗯

**Comment by kdplus** [comment]
```
# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 扯
subtitle:
description:
author: Yusn_mika_soso
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: next
avatar: http://img5.duitang.com/uploads/item/201411/11/20141111185117_vRBBi.thumb.700_0.jpeg

# Social links
social:
  github: https://github.com/kdplus
  twitter: https://twitter.com/15058617922
  weibo: http://weibo.com/maxsn
  douban: http://douban.com/people/your-user-name
  zhihu: http://www.zhihu.com/people/your-user-name
  facebook: https://www.facebook.com/profile.php?id=100003360406407

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:kdplus/kdplus.github.io.git
  branch: master
  
menu: 
  home: /
  archives: /archives
  tags: /tags
  about: /about

# =============================================================================
# NexT Theme configuration
# =============================================================================

# 多说帐号
#duoshuo_shortname: your-duoshuo-shortname

# DISQUS 帐号 （如果已经设置 多说 帐号，此选项将被跳过）
disqus_shortname: kdplus

favicon: /favicon.ico

# 代码高亮主题
# available: normal | night | night eighties | night blue | night bright
highlight_theme: normal

google_analytics: 15058617922sn@gmail.com
# =============================================================================
# End NexT Theme configuration
# =============================================================================
```

**Comment by kdplus** [comment]
```
menu:
  home: /
  archives: /archives
  tags: /tags
  about: /about

# Place your favicon.ico to /source directory.
favicon: /favicon.ico

# Set rss to false to disable feed link.
# Leave rss as empty to use site's feed link.
# Set rss to specific value if you have burned your feed already.
rss:

# Icon fonts
# Place your font into next/source/fonts, specify directory-name and font-name here
# Avialable: default | linecons | fifty-shades | feather
icon_font: default
#icon_font: fifty-shades
#icon_font: feather
#icon_font: linecons

# Code Highlight theme
# Available value: normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: normal


# MathJax Support
mathjax:


# Mist
# 使用 Mist 主题
scheme: Mist


## DO NOT EDIT THE FOLLOWING SETTINGS
## UNLESS YOU KNOW WHAT YOU ARE DOING

# Use velocity to animate everything.
use_motion: true

# Fancybox
fancybox: true

# Static files
vendors: vendors
css: css
images: images

# Theme version
version: 0.3.0rc4

```
