### ISSUE TITLE
Local search is not available

### ISSUE THREAD

**Issue by emptyxl** [iissnan/hexo-theme-next#1929]
My blog is here:[hellohxk.com](https://hellohxk.com) and local search function is not available. 
My config is here:

```
local_search:
  enable: true
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 1
```

It worked normally when i set up my blog and i never update next theme's source code and modify the config.
