### ISSUE TITLE
怎样套用别人的模板

### ISSUE THREAD

**Issue by anson2416** [iissnan/hexo-theme-next#1940]
我成功加载了Next主题。但是发现左边没有统计栏/个人简介。
在Github上看到很多别人的注意，例如 [Alynx](http://sh.alynx.xyz)。
请问怎样可以套用别人的模板？

**Comment by Raincal** [comment]
要有他配置的源代码才行 你可以参考下我的 [传送门](https://github.com/Raincal/blog)
个人简介那种页面 需要单独生成
`hexo new page about` 
然后到 blog -> source -> about -> index.md 里指定 **type** 为 **about**
最后到主题配置把 **about** 那行注释去掉
![2017-10-12 07 16 08 pm](https://user-images.githubusercontent.com/6279478/31493477-f8a507bc-af14-11e7-8044-51f9c4176497.png)

**Comment by anson2416** [comment]
那怎样生成文章目录啊？找了很久都不知道怎样设置。在主题的配置文件里面默认已经打开了toc，但是就是不成功。

```
# Table Of Contents in the Sidebar
toc:
  enable: true

  # Automatically add list number to toc.
  number: true

  # If true, all words will placed on next lines if header width longer then sidebar width.
  wrap: false

```
