### ISSUE TITLE
CSS代码有时候无法高亮

### ISSUE THREAD

**Issue by anson2416** [iissnan/hexo-theme-next#1947]
通过引用代码块并添加语言css，但是在博客里面有很多时候都无法**高亮**。请问应该怎样修改设置。

```css
// 菜单栏.menu {	
margin-top: 20px;	
padding-left: 0;	
text-align: center;	
background: rgba(240, 240, 240, 0.5);	
margin-left: auto;	
margin-right: auto;	
width: 530px;	
border-radius: initial;
}
```

**Comment by ivan-nginx** [comment]
Don't understand u, write in English if not solved. If solved, close it please. Thank's!

**Comment by geekrainy** [comment]
请给出 demo.

**Comment by zhuzhuyule** [comment]
you can set highlight code ***language*** ,! 
for example:
````
```language
Code Area !
```
````

````
```css
// 菜单栏
.menu {	
margin-top: 20px;	
padding-left: 0;	
text-align: center;	
background: rgba(240, 240, 240, 0.5);	
margin-left: auto;	
margin-right: auto;	
width: 530px;	
border-radius: initial;
}
```
````

```css
// 菜单栏
.menu {	
margin-top: 20px;	
padding-left: 0;	
text-align: center;	
background: rgba(240, 240, 240, 0.5);	
margin-left: auto;	
margin-right: auto;	
width: 530px;	
border-radius: initial;
}
```

## Tip
the **comments** of `CSS` are use of  `/*...*/`
```css
/*菜单栏*/
.menu {	
margin-top: 20px;	
padding-left: 0;	
text-align: center;	
background: rgba(240, 240, 240, 0.5);	
margin-left: auto;	
margin-right: auto;	
width: 530px;	
border-radius: initial;
}
```
## Other
if you need more **MarkDown** info, you can look [HEXO下的Markdown语法(GFM)写博客](http://zhuzhuyule.xyz/2017/01/10/HEXO/HEXO%E4%B8%8B%E7%9A%84Markdown%E8%AF%AD%E6%B3%95(GFM)%E5%86%99%E5%8D%9A%E5%AE%A2/);
if you need more **highlight extend** method, you can look [HEXO下的语法高亮拓展修改](http://zhuzhuyule.xyz/2017/09/09/HEXO/HEXO%E4%B8%8B%E7%9A%84%E8%AF%AD%E6%B3%95%E9%AB%98%E4%BA%AE%E6%8B%93%E5%B1%95%E4%BF%AE%E6%94%B9/).
