### ISSUE TITLE
Double 'theme' parameter when using hexo datafiles

### ISSUE THREAD

**Issue by maddovr** [iissnan/hexo-theme-next#1948]
When using hexo datafiles(one big configuration file in _data) the value 'theme' is repeated twice, once in hexo site _config.yml and the other time in the footer option, causing an error which can only be avoided by deleting this option from the configuration file. Is it possible to rename it?

NeXT v5.1.3

**Comment by ivan-nginx** [comment]
Don't understand in what triuble. Can u explain it totally? Some examples or reproducte steps, etc. What options u enable, what disable? Need more info.

**Comment by maddovr** [comment]
When copypasting both *_config.yml* in hexo site root and next *_config.yml* in one big file, i.e *next.yml* in source/_data, with the latest version of next theme YAML throws out an error due to a duplicate variable, in this case theme:

The first one in hexo config determines what theme the site must use:

```# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next 
```

The second one is the new NeXT copyright option down in the footer:

```
# Hexo link (Powered by Hexo).
  powered: true

  theme:
    # Theme & scheme info link (Theme - NexT.scheme).
    enable: true
    # Version info of NexT after scheme info (vX.X.X).
    version: false
```

This behavior causes YAML to throw out an error and crash, thus the site cannot be built unless you either delete the footer variable or stop using hexo datafiles for personalization(which prevents you from updating the theme without losing the config[ofc you might use a backup instead]). As such, is it possible to just rename that variable in order to prevent any conflict?

**Comment by ivan-nginx** [comment]
I see now.
U add full NexT theme configs with `footer`, e.g.:
```yml
footer:
  # Specify the date when the site was setup.
  # If not defined, current year will be used.
  #since: 2015

  # Icon between year and copyright info.
  icon: user

  # If not defined, will be used `author` from Hexo main config.
  copyright:
  # -------------------------------------------------------------
  # Hexo link (Powered by Hexo).
  powered: true

  theme:
    # Theme & scheme info link (Theme - NexT.scheme).
    enable: true
    # Version info of NexT after scheme info (vX.X.X).
    version: true
```
Or u add only ` theme:` without parent `footer:` configuration? Because basically this configs must readed by Hexo as `footer: theme: ...`.
