### ISSUE TITLE
algolia搜索怎么进行全文搜索呢？我看题主的搜索都可以搜索到content内容

### ISSUE THREAD

**Issue by kanlidy** [iissnan/hexo-theme-next#1957]
### I agree and want to create new issue 

- [X] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [X] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
使用algolia搜索，可以搜到到文章内的内容，显示出搜索结果相对应的文章。与题主一样

### Actual behavior 
按照http://theme-next.iissnan.com/third-party-services.html#search-system#Algolia进行配置之后，只能搜索出标题，而文章内容不能搜索。

### Steps to reproduce the behavior 
1. 安装hexo
2. 安装next主题
3. 申请algolia API，全部开放权限； 
4. 配置_config.yml，配置主题_config.yml

```
algolia_search:
  enable: true
  hits:
    per_page: 20
  labels:
    input_placeholder: 输入关键词进行搜索
    hits_empty: "找不到关于“${query}”的文章"
    hits_stats: "共找到 ${hits} 篇文章，花了 ${time} ms"
```

* Link to demo site with this issue:  N/A 因为是本地测试，没有线上搜索。
* Link(s) to source code or any usefull link(s): http://notes.iissnan.com/ 比如搜索输入：”随后再进入”，会显示结果：“使用 Travis CI 自动更新 GitHub Pages”

### Hexo Information

```
[liwei@localhost blog]$ hexo -v
hexo: 3.3.9
hexo-cli: 1.0.3
os: Darwin 16.7.0 darwin x64
http_parser: 2.7.0
node: 6.11.0
v8: 5.1.281.102
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k
```

### NexT Information

**NexT Version:**

```
[] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[X] All schemes
[] Muse
[] Mist
[] Pisces
[] Gemini
```

### Other Information 
Chrome Latest

package.json

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.3.9"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-algolia": "^1.2.3",
    "hexo-deployer-git": "^0.3.1",
    "hexo-deployer-rsync": "^0.1.3",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-json-content": "^3.0.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0"
  }
}
```

**Comment by kanlidy** [comment]
更换插件：https://github.com/LouisBarranqueiro/hexo-algoliasearch

**Comment by kanlidy** [comment]
修改https://github.com/kanlidy/hexo-theme-next/blob/master/source/js/src/algolia-search.js#L6
为了保证与插件的关键字进行统一。

```
algolia:
  appId: "Z7A3XW4R2I"
  apiKey: "12db1ad54372045549ef465881c17e743"
  adminApiKey: "40321c7c207e7f73b63a19aa24c4761b"
  chunkSize: 5000
  indexName: "my-hexo-blog"
  fields:
    - title
    - tags
    - slug
    - excerpt
    - excerpt:strip
    - photos
    - gallery
    - content:strip
```

这样就能支持全文搜索了。

@iissnan
