### ISSUE TITLE
gitment redirect_uri_mismatch

### ISSUE THREAD

**Issue by Ahaochan** [iissnan/hexo-theme-next#1970]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 
I want to add Gitment in MyBlog.

### Actual behavior 
When I click **【登入 with GitHub】** button, the url redirect to 
```
https://ahaochan.github.io/?
error=redirect_uri_mismatch&
error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&
error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch
```

### Steps to reproduce the behavior 
1. I create [OAuth Apps](https://github.com/settings/developers). The Setting just like:
```
Application name: Ahaochan
Homepage URL: https://ahaochan.github.io
Authorization callback URL: https://ahaochan.github.io
```
2. I get My Client ID and Client Secret
3.  I add setting in `source/_data/next.yml`.
```yml
gitment:
  enable: true
  mint: true # RECOMMEND, A mint on Gitment, to support count, language and proxy_gateway
  count: true # Show comments count in post meta area
  lazy: false # Comments lazy loading with a button
  cleanly: false # Hide 'Powered by ...' on footer, and more
  language: # Force language, or auto switch by theme
  github_user: Ahaochan # MUST HAVE, Your Github ID
  github_repo: Ahaochan.github.io # MUST HAVE, The repo you use to store Gitment comments
  client_id: d**********7 # MUST HAVE, Github client id for the Gitment
  client_secret: 1****************c # EITHER this or proxy_gateway, Github access secret token for the Gitment
  proxy_gateway: # Address of api proxy, See: https://github.com/aimingoo/intersect
  redirect_protocol: # Protocol of redirect_uri with force_redirect_protocol when mint enabled

```
4. I use `-- config source/_data/next.yml ` command to deploy my blog

* Link to demo site with this issue: [MyBlog](https://ahaochan.github.io/posts/The%20Best%20practice%20for%20create%20Utils%20class.html)
* Link(s) to source code or any usefull link(s): N/A

### Hexo Information

```
Hexo3
```

### NexT Information

**NexT Version:**

```
[x] Latest Master branch.
[] Latest Release version.
[] Old version - 
```

**NexT Scheme:**

```
[] All schemes
[] Muse
[x] Mist
[] Pisces
[] Gemini
```
