### ISSUE TITLE
代码块显示问题

### ISSUE THREAD

**Issue by astraylinux** [iissnan/hexo-theme-next#199]
代码过长的时候
![](http://res.astraylinux.com/markdown/md-highlight-problem1.png)

我看到有一些md的显示是这样的
![](http://res.astraylinux.com/markdown/md-highlight-problem2.png)

**Comment by astraylinux** [comment]
这个有办法设置吗

**Comment by iissnan** [comment]
看不到你发的图片

**Comment by astraylinux** [comment]
https://camo.githubusercontent.com/abdec5f5ce2ab495b132713ff494d095d751d7b4/687474703a2f2f7265732e6173747261796c696e75782e636f6d2f6d642d686967686c696768742d70726f626c656d322e706e67

地址是这样的。。。 我还以为他存了
我再发一个

**Comment by astraylinux** [comment]
[http://res.astraylinux.com/markdown/md-highlight-problem1.png](http://res.astraylinux.com/markdown/md-highlight-problem1.png)
![](http://res.astraylinux.com/markdown/md-highlight-problem1.png)

[http://res.astraylinux.com/markdown/md-highlight-problem2.png](http://res.astraylinux.com/markdown/md-highlight-problem1.png)
![](http://res.astraylinux.com/markdown/md-highlight-problem2.png)

**Comment by iissnan** [comment]
添加到 `_custom/custom.styl`

```css
.post pre {
  white-space: pre-wrap;       /* css-3 */
  white-space: -moz-pre-wrap;  /* Mozilla, since 1999 */
  white-space: -pre-wrap;      /* Opera 4-6 */
  white-space: -o-pre-wrap;    /* Opera 7 */
  word-wrap: break-word;       /* Internet Explorer 5.5+ */
}
```
