### ISSUE TITLE
Font can't display correctly

### ISSUE THREAD

**Issue by Vincentqyw** [iissnan/hexo-theme-next#2012]
### I agree and want to create new issue 

- [x] Yes, I was on [Hexo Docs page](https://hexo.io/docs/), especially on [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I was on [NexT Documentation Site](http://theme-next.iissnan.com/).
- [x] And yes, I already searched for current [issues](https://github.com/iissnan/hexo-theme-next/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

***

### Expected behavior 

When I change **font family**, the corresponding font can display correctly on different browsers and machines.

### Actual behavior 

When I change **font family**, the corresponding font style can't display. Eg, the global font family is Monda, while actually the font in [my blog](https://www.vincentqin.tech/collections/) is not that font.

![](http://oofx6tpf6.bkt.clouddn.com/17-11-29/23852811.jpg)

And, when I switch to another browser, it turns to be like this:

![](http://oofx6tpf6.bkt.clouddn.com/17-11-29/67414826.jpg)

I don't know what causes this error...

### Steps to reproduce the behavior 

The configuration of font is default, which is as following:
``` yml
font:
  enable: true

  # Uri of fonts host. E.g. //fonts.googleapis.com (Default).
  host: 

  # Font options:
  # `external: true` will load this font family from `host` above.
  # `family: Times New Roman`. Without any quotes.
  # `size: xx`. Use `px` as unit.

  # Global font settings used on <body> element.
  global:
    external: true
    family: Monda
    size:  

  # Font settings for Headlines (h1, h2, h3, h4, h5, h6).
  # Fallback to `global` font settings.
  headings:
    external: true
    family: Roboto Slab
    size:

  # Font settings for posts.
  # Fallback to `global` font settings.
  posts:
    external: true
    family: Garamond

  # Font settings for Logo.
  # Fallback to `global` font settings.
  logo:
    external: true
    family: Lobster Two
    size: 24

  # Font settings for <code> and code blocks.
  codes:
    external: true
    family: true
    size: PT Mono
```

* Link to demo site with this issue: N/A
* Link(s) to source code or any usefull link(s): N/A

### Hexo Information

```
hexo: 3.3.1
hexo-cli: 1.0.3
os: Windows_NT 10.0.14393 win32 x64
http_parser: 2.7.0
node: 6.1.0
v8: 5.0.71.35
```

### NexT Information

**NexT Version:**

- [x] Latest Master branch.
- [ ] Latest Release version.
- [ ] Old version - 

**NexT Scheme:**

- [ ] All schemes
- [ ] Muse
- [ ] Mist
- [ ] Pisces
- [x] Gemini
