### ISSUE TITLE
Mist下怎么使首页文章标题、read more 居中 ?

### ISSUE THREAD

**Issue by LINWAYNE** [iissnan/hexo-theme-next#205]
默认左对齐看起来有点难受，求解决

**Comment by iissnan** [comment]
Mist 默认是左对齐的，如果需要居中的话要手动修改样式文件：

`_custom/variables.styl` 新增：

```css
$site-meta-text-align = left;
```

`_custom/custom.styl` 新增：

```css
.post-more-link {
    text-align: center;
}
```

**Comment by LINWAYNE** [comment]
我修改了之后，发现是read more 居中了，标题没有变化T.T

**Comment by iissnan** [comment]
或者 

```css
.posts-expand .post-title, .posts-expand .post-meta {
  text-align: center;
}
```
