### ISSUE TITLE
How to make background picture responsible for mobile?

### ISSUE THREAD

**Issue by zehuichen123** [iissnan/hexo-theme-next#2077]
**Scheme**:Muse
**Next version**:v5.1.3
**hexo imformation:**
```
hexo: 3.4.4
hexo-cli: 1.0.4
os: Darwin 17.3.0 darwin x64
http_parser: 2.5.2
node: 4.4.4
v8: 4.5.103.35
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2h
```
I changed my Next theme's background picture like this: <a href="https://lovesnowbest.site">loveSnowBest's blog</a> by writing like this in `custom.styl (next/source/ css/_custom/custom.styl)`:
```css
body {
    background:url(https://r.photo.store.qq.com/psb?/V13ngZ4i4Zyl6Y/tzjaynxSmI8PTFVL5rQlET8x9uMcDGDHB3M44i2Bor0!/r/dPMAAAAAAAAA);
    background-position: center 0;  
    background-repeat: no-repeat;  
    background-attachment: fixed;  
    background-size: cover;  
    -webkit-background-size: cover;  
    -o-background-size: cover;  
    -moz-background-size: cover;  
    -ms-background-size: cover;  
}
```
And this setting performs well on desktop but when it comes to mobile, it failed to fill whole screen. It just showed in the middle of the mobile page,just like this:
<a href="http://r.photo.store.qq.com/psb?/V13ngZ4i1rva8i/Q6*8DUy8fLzMxhYZKtGgco89u0TQjaCc7bHH7qqMgB4!/r/dPIAAAAAAAAA">screenshot1</a>
<a href="http://r.photo.store.qq.com/psb?/V13ngZ4i1rva8i/3pvwHMTLgTHc29590stCoVVhoDta3ErcagIOP1STtSE!/r/dPIAAAAAAAAA">screenshot2</a>
<a href="http://r.photo.store.qq.com/psb?/V13ngZ4i1rva8i/Ppamsr7ouYVZYILpPuulffhR3q*IyTSInNZklHqnztc!/r/dGgBAAAAAAAA">screenshot3</a>
<a href="http://r.photo.store.qq.com/psb?/V13ngZ4i1rva8i/99wNF..a1edAtVO4EVF4Y*uqt5hxPzK1RcvdNIBUnr8!/r/dF4BAAAAAAAA">screenshot4</a>
Or you can just visit <a href="https://lovesnowbest.site">my page</a> with your phone on your own.  
Sorry for my lack of html and css knowledge that I can's solve this problem though I searched it on google. I'd appreciated much if anyone can help me with it. :)
