### ISSUE TITLE
How do I configure the posts sorted by update time rather than create time?

### ISSUE THREAD

**Issue by emptyxl** [iissnan/hexo-theme-next#2082]
I have changed the `update_at` to `true` in next theme's `_config,xml`:

```
# Post meta display settings
post_meta:
  item_text: true
  created_at: true
  updated_at: true
  categories: true
```

And the config in my posts like this:

```
---
title: xxx
layout: post
date: 2017-09-21 22:44:23
keywords: xx
tags:
    - xx
    - xx
categories:
    - xx
---
```

Both created time and updated time are showed and the updated time filed seems to correspond to the modification time of the file.It's obviously sorted by created time,How can i change it sorted by updated time?
@ivan-nginx
