### ISSUE TITLE
Every page starts with opened sidebar

### ISSUE THREAD

**Issue by mcepl** [iissnan/hexo-theme-next#239]
When I open any page with your theme (otherwise very pretty, thank you!) huge window with table of contents openes on the side.
![screenshot from 2015-06-22 07-08-52](https://cloud.githubusercontent.com/assets/198999/8275817/975c8390-18ad-11e5-9218-ff3e135b8e42.png)
How to make the ToC closed per default? (using Firefox 38 on Linux).

**Comment by mcepl** [comment]
And nothing has changed, when I changed `themes/next/_config.yml` value of `sidebar` to `hide`.

**Comment by iissnan** [comment]
I found that style rules for sidebar had been re-written by the rules:

```css
div.sidebar {
  margin: 0 0 0.5em 1em;
  border: medium outset;
  padding: 1em;
  background-color: #ffffee;
  width: 40%;
  float: right;
  clear: right;
}
```

These rules are not provided by NexT theme. You can remove this style rules or just add another rule if you don't want to show sidebar.

```css
div.sidebar { display: none; }
```
