### ISSUE TITLE
顶部菜单栏标题显示问题

### ISSUE THREAD

**Issue by wmhjeremy** [iissnan/hexo-theme-next#243]
我在next主题文件夹下的 _config.yml文件中修改
menu:
  首页: /
  归档: /archives
  #标签: /tags
  分类: /categories
  关于: /about
但是在网页中顶部菜单栏标题却显示为Menu.首页  Menu.归档 这样子的效果，这是什么原因啊？
多谢了~^_^

**Comment by iissnan** [comment]
简单来说，你只要将 menu 里面的那部分修改回：

```yml
menu:
  home: /
  archives: /archives
  categories: /categories
  tags: /tags
  about: /about
```

然后将 `language` 设置成 `zh-Hans` 就可以了。

----

往细里说，你所修改的是 key 部分，这些 key 有对应的翻译。以 `menu.home` 为例，当 Hexo 编译的时候，会到 languages 目录下找寻对应的 `menu.home` ；在 `zh-Hans.yml` 中 `menu.home` 是 `首页`，在 `default.yml` 中 `menu.home` 是 `Home`。
