### ISSUE TITLE
duoshuo_info 应当如何填写？

### ISSUE THREAD

**Issue by Dynamicer** [iissnan/hexo-theme-next#289]
填写 `32d89ecades8i76s6e7d9f9a053d` 这样的密钥，在执行 `hexo g` 时，提示 `JS-YAML: bad indentation of a mapping entry at line 72, column 12:
      ua_enable: true
               ^` 。

**Comment by Dynamicer** [comment]
仔细看了文档，原来是填写 `shortname` ，但是我填写 `duoshuo_info: dynamicer` 和 `duoshuo_info: "dynamicer"` 时仍然存在一样的问题。

**Comment by iissnan** [comment]
我试着配置了一下，没有什么问题。

配置如下：

```
duoshuo_info:
  ua_enable: true
  admin_enable: true
  user_id: xxxxxx
```

`duoshuo_info` 那栏不要填写
