### ISSUE TITLE
首页分页和归档分页不同是如何做到的？

### ISSUE THREAD

**Issue by lurrpis** [iissnan/hexo-theme-next#30]
你好，很喜欢你的主题，现在我也在使用，
不过稍微做了点改动，请海涵!
[我的博客](http://lurrpis.com/)
看到你的blog的首页为展示`5篇文章/页`，而归档页展示为`20篇文章/页`，
请问是在`config`里配置还是在代码里实现的？

谢谢！

**Comment by iissnan** [comment]
没关系。我也正在着手在 NexT 基础上做一个紧凑的版本，跟你的有点类似。

不同的分页设置需要 Hexo 3 版本，通过 `npm i --save` 以下 plugin：

- [hexo-generator-index](https://github.com/hexojs/hexo-generator-index)
- [hexo-generator-archive](https://github.com/hexojs/hexo-generator-archive)
- [hexo-generator-tag](https://github.com/hexojs/hexo-generator-tag)

然后在站点的 `_config.yml` 中设置，例如：

```
index_generator:
  per_page: 5

archive_generator:
  per_page: 20
  yearly: true
  monthly: true

tag_generator:
  per_page: 10
```
