### ISSUE TITLE
categories已经设置， 但侧边栏，分类没有显示为链接。tag正常

### ISSUE THREAD

**Issue by young40** [iissnan/hexo-theme-next#300]
站点的_config.yml中这样设置。

```
menu:
  home: /
  archives: /archives
  categories: /categories
  tags: /tags
  about: /about

```

浏览器地址栏直接输入categories/ 访问也正常。

hexo: 3.1.1
