### ISSUE TITLE
当代码过长，在手机上没有横向滚动条，导致代码无法看全

### ISSUE THREAD

**Issue by littledu** [iissnan/hexo-theme-next#353]
当代码过长，在手机上没有横向滚动条，导致代码无法看全

解决方法：
在 custom.styl 增加

```css
.highlight {
  -webkit-overflow-scrolling: touch;
}
```

即可。
