### ISSUE TITLE
是否支持首页中的文章末尾有tag

### ISSUE THREAD

**Issue by sabrinaluo** [iissnan/hexo-theme-next#36]
请问在哪里设置？谢谢:)

**Comment by iissnan** [comment]
我把首页的 tags 去掉了。 :sweat_smile:

**Comment by minoscc** [comment]
在`~/themes/next/source/css/_custom.styl` 添加自定义样式`inline`或者`block`啥的
```css
.page-home .post-tags {
    display: inline;
}
```
