### ISSUE TITLE
Mist开启后怎样自定义logo及主题图标

### ISSUE THREAD

**Issue by PascoCoder** [iissnan/hexo-theme-next#360]
喜欢Mist的主题，开启Mist后按照教程想把侧边栏的social自定义成社交网站的额logo，结果发现没有改变。请问我应该在哪里更改styl文件，谢谢：）

**Comment by iissnan** [comment]
侧边栏的 Social 目前还不支持自定义

**Comment by S4IKO** [comment]
@iissnan 请问该主题还会继续更新吗？

**Comment by iissnan** [comment]
@S4IKO  会

**Comment by chenjuntong** [comment]
@iissnan 请问您网站上的icon是如何做到的呢

**Comment by iissnan** [comment]
@chenjuntong 你是侧栏菜单的图标吗？

在配置文件里：

```
# Social links
 # social:
   #GitHub:
   #Others:
 
 # Social Icons
 social_icons:
   enable: true
   # Icon Mappings
   GitHub: github
   Twitter: twitter
   Weibo: weibo
```

`social_icons` 里设置的 icon 名字会匹配到 FontAwesome 里。
