### ISSUE TITLE
public/tags/foo/ is empty

### ISSUE THREAD

**Issue by chikyukotei** [iissnan/hexo-theme-next#365]
I did following commands.

```
hexo new page "tags"
# add *type: tags* in source/tags/index.md
hexo serve
```

but cannot GET /tags/foo/.
Then, Although i saw public/tags/foo in my repository, public/tags/foo was empty.

what should I do?

**Comment by winterTTr** [comment]
Just my guess
- do you enable the tag setting in theme _config.yml file?
- try to generate your site again via `hexo generate`
- try to delete the `db.json` file and `hero generate` again

**Comment by chikyukotei** [comment]
> do you enable the tag setting in theme _config.yml file?

Regarding tag setting in theme _config.yml file, i don't do anything in particular.
I just use default settings.
``` yaml
# when running hexo in a subdirectory (e.g. domain.tld/blog), remove leading slashes ( "/archives" -> "archives" )
menu:
  home: /
  #categories: /categories
  #about: /about
  archives: /archives
  tags: /tags
  #commonweal: /404.html
```

> try to generate your site again via  hexo generate
> try to delete the  db.json  file and  hero generate  again

I tried these, but don't works.
