### ISSUE TITLE
自定义菜单

### ISSUE THREAD

**Issue by haskellcamargo** [iissnan/hexo-theme-next#411]
你好。
我遇到一些麻烦, 而试图以自定义主菜单。
![menu](https://cloud.githubusercontent.com/assets/7553006/10421443/fba2626a-707e-11e5-917e-fa35fe496c60.png)

当我改变菜单不同的东西, 它没有选择更改图标。

在我的菜单, 我有:
```yaml
menu:
  home: /
  #categories: /categories
  about: /about-me
  talks: /talks
  projects: /projects
  #commonweal: /404.html
```
如何自定义图标和文字?
我对不起我的坏中国。 我是巴西人。
谢谢, Marcelo Camargo.
