### ISSUE TITLE
如何去掉自定义菜单的前缀Menu.

### ISSUE THREAD

**Issue by AlanCheen** [iissnan/hexo-theme-next#412]
自己多定义了一些菜单item,但是每个都会自动加上Menu. 前缀,我想去掉,怎么去?
先谢过!

**Comment by iissnan** [comment]
这个 Menu. 前缀实际上是 Hexo 未找到对应的翻译导致的。 你可以修改下你所选择的语言文件（位于 `languages` 目录下）。

假定你的菜单新增一项 `something`：

```yml
menu:
  home: /
  something: /something
```

同时，你使用的是中文简体，就需要编辑 `languages/zh-Hans.yml`，修改 `menu` 下的定义：

```yml
menu:
  home: 首页
  something: 三星
```

这样，就会自动 Hexo 就会自动使用 "三星" 作为新 item 的文本。
