### ISSUE TITLE
icon_font:  项不生效

### ISSUE THREAD

**Issue by SPRING-Z** [iissnan/hexo-theme-next#446]
文档说默认提供4套，我挨个试了一次，都不生效。

**Comment by iissnan** [comment]
:sweat_smile: 新版本中已经去掉了，统一使用 FontAwesome。这个功能定制很麻烦。

**Comment by SPRING-Z** [comment]
@iissnan 那个主页站点名前面的那个太阳是怎么加上去的，我的就显示一个黑方框，http://3.14159265.com

**Comment by iissnan** [comment]
那个图标去掉了，改称了自定义 Logo 的方式。自定义 Logo 的配置如下：

```yml
# Custom Logo.
# !!Only available for Default Scheme currently.
# Options:
#   enabled: [true/false] - Replace with specific image
#   image: url-of-image   - Images's url
custom_logo:
  enabled: false
  image:
```
