### ISSUE TITLE
侧边栏社交链接Font awesome图标显示不全

### ISSUE THREAD

**Issue by HuberyLee** [iissnan/hexo-theme-next#450]
侧边栏社交链接图标显示不全，看了一下代码，作者应该是直接将链接的名称加在fa-的后面从Font awesome中获取对应图标的，但有些图标可能不存在，所以就出现的部分图标不显示的问题，作者看看有什么解决方法呢？
<img width="304" alt="screen shot 2015-10-23 at 10 32 44 pm" src="https://cloud.githubusercontent.com/assets/11664307/10695599/127b6ca0-79d7-11e5-8586-7c811b7dad68.png">
<img width="479" alt="screen shot 2015-10-23 at 10 27 44 pm" src="https://cloud.githubusercontent.com/assets/11664307/10695598/127a68a0-79d7-11e5-8898-ce00523a37b1.png">

**Comment by iissnan** [comment]
确实有一个方案。与 Menu 的 icon 定制方式一样，社交链接也提供了一个称为  Icon Mapping 的方法。
示例配置如下：

```yml
# Social links
social:
  GitHub: http://github.com
  知乎: http://zhihu.com

social_icons:
  enable: true
  # Icon Mappings
  GitHub: github
  Twitter: twitter
   知乎: global
```
