### ISSUE TITLE
关于侧边栏社交链接的显示问题

### ISSUE THREAD

**Issue by BigPa** [iissnan/hexo-theme-next#525]
按照[文档](http://theme-next.iissnan.com/theme-settings.html#侧边栏社交链接)设置社交链接，效果如图。
<img width="154" alt="2015-11-21 11 50 13" src="https://cloud.githubusercontent.com/assets/9963287/11316554/cf87610c-9046-11e5-9b6f-e26003931ebd.png">

请问该如何处理？

**Comment by xavierchow** [comment]
检查一下：
```
social:
  GitHub: http://github.com/defunkt
  #Others:

# Social Icons
social_icons:
  enable: true
  # Icon Mappings
  GitHub: github
```
或者把你的配置贴上来？

**Comment by BigPa** [comment]
在hexo配置中
```
social:
  GitHub: https://github.com/BigPa
  ZhiHu: http://www.zhihu.com/people/bigpa
```
在next配置中
```
# Social Icons
social_icons:
  enable: false
    #  Icon Mappings
  GitHub: github
  #Twitter: twitter
  #Weibo: weibo
```
