### ISSUE TITLE
页面加载缓慢

### ISSUE THREAD

**Issue by leejanfin** [iissnan/hexo-theme-next#53]

**Comment by iissnan** [comment]
刚试着打开你的博客，貌似第一次访问主要的时间在于下载 Lato 字体上，竟然使用了将近 6s ~~

**Comment by leejanfin** [comment]
现在访问速度又貌似正常了，是不是因为是刚刚部署上去的原因呢？

**Comment by iissnan** [comment]
侧边栏 Social 地址可以自己加，例如：

```
- GitHub: xxx
- Weibo: xxx
- Email: mailto: my-awesome-email-address
```

**Comment by leejanfin** [comment]
Email这个写法会报错，错误信息：
[error] { name: 'HexoError',
  reason: 'incomplete explicit mapping pair; a key node is missed',

**Comment by iissnan** [comment]
```
social:
  GitHub: xxx
  Weibo: xxx
  Email: mailto:my-awesome-email-address
```
