### ISSUE TITLE
category 和 tag 列表的文章标题与时间位置重叠

### ISSUE THREAD

**Issue by dracodoc** [iissnan/hexo-theme-next#540]
![2015-11-27_152459](https://cloud.githubusercontent.com/assets/1730496/11447831/0fa34bba-951b-11e5-8e1d-15443dcea2cd.png)

找了一下css，只找到了如何修改页面本身的css，没有找到如何修改theme的什么地方。

**Comment by iissnan** [comment]
有更改了前面时间的样式，默认字号没有这么大：

```css
.posts-collapse .post-meta {
  position: absolute;
  font-size: 12px;
  left: 20px;
  top: 5px;
}
```
