### ISSUE TITLE
菜单栏固定的实现

### ISSUE THREAD

**Issue by zhaoweiwang** [iissnan/hexo-theme-next#554]
![image](https://cloud.githubusercontent.com/assets/4099495/11735423/03ad0b20-9ffc-11e5-99f1-90cf930007e8.png)

很久没来，才发现仓主的博客模板改动已经很大。
想了解一下，我想固定住老版中的这个菜单栏，让鼠标滚轮滚下去的时候，菜单栏依然显示，怎么实现呢？

**Comment by kisnows** [comment]
找到这个元素的class，假设它的class是header，在styl文件找到它的样式，然后加上下面这些样式
```css
.header{
   position:fixed;
   top: 0;
   left: 0;
   width: 100%;
}
```
