### ISSUE TITLE
关于markdown自动抽取文章目录的问题

### ISSUE THREAD

**Issue by Sayary** [iissnan/hexo-theme-next#56]
关于网页界面自动抽取格式的问题，如果我自己在次级标题里加入1.1这种格式的话，仍然会重复添加，能不能在config里加一项禁用掉这条特性呢？

具体的情况大体如下：

![image](https://cloud.githubusercontent.com/assets/1910278/6735999/926f3450-ce38-11e4-9178-bef2101f4e1b.png)

**Comment by mingmings** [comment]
我也出过，后来直接改掉文章前面的标题了

**Comment by jiangxy** [comment]
这种情况就不要自己加编号了
否则侧边栏还有何用

**Comment by iissnan** [comment]
Yes. May I can add an option for this.

**Comment by iissnan** [comment]
添加了一个 `toc_list_number` 选项，默认是 `true`，即会自动生成索引号。
设置为 `false` 来禁用自动生成索引号。

**Comment by mingmings** [comment]
@iissnan 这个是添加在 `markdown` 文档里还是站点配置文件中

**Comment by iissnan** [comment]
@mingmings 在站点配置文件中

**Comment by jiangxy** [comment]
@iissnan  似乎`toc_list_number`默认是false？我更新后不显示索引号了。手动设置为true才显示。

**Comment by iissnan** [comment]
@jiangxy 默认应该是 `true`，这个 Issue 中引用的那个提交是 `false`，我在下一个提交中修改过来了。见：https://github.com/iissnan/hexo-theme-next/commit/d01f7e1bc9f787c4cf192ea9436669ddae7d74a5

**Comment by CaliosD** [comment]
弱弱的说一句，是不是在主题的配置文件中。。

**Comment by anson2416** [comment]
想问下，在NexT主题的配置文件已经设置TOC，但是并没有显示出来。还需要设置什么吗？

```
# Table Of Contents in the Sidebar
toc:
  enable: true

  # Automatically add list number to toc.
  number: true

  # If true, all words will placed on next lines if header width longer then sidebar width.
  wrap: false
```
