### ISSUE TITLE
Pisces文章目录跟随屏幕滚动吧

### ISSUE THREAD

**Issue by willin** [iissnan/hexo-theme-next#586]
http://blog.willin.wang/posts/2015/wulian-1st-year/

**Comment by ameol** [comment]
怎么使用Pisces啊，我这为什么只有Mist

**Comment by LeoiOS** [comment]
+1
https://github.com/iissnan/hexo-theme-next/issues/576

**Comment by VuePack** [comment]
@LeoiOS 
@willin 
pisces.js 倒数第一行加入 

```js
  $(window).scroll(function(){
      var scrollTop = $(window).scrollTop();
      if(scrollTop > $('.header-inner').height()){
          $('#header').hide();
          $('#sidebar').addClass('scroll-sidebar');
      }else{
          $('#header').show();
          $('#sidebar').removeClass('scroll-sidebar');
      }
  });
```
```css
.scroll-sidebar{
    position:fixed;
    top:0px;
    margin-top:0px !important;
}
```
具体效果：
[website](http://likr.cn/)
