### ISSUE TITLE
使用next主题时hexo generate生成主页文章数量不完整

### ISSUE THREAD

**Issue by winterTTr** [iissnan/hexo-theme-next#594]
我也是无意中才注意到的，暂时不确定是我个人的配置问题，还是next对网站编译的影响，iissnan可以给点建议。我刚刚重新git clone一份自己的代码，然后再次hexo g了一次，结果是一样的。
我的详细配置全部在我的github里面 https://github.com/winterTTr/winterTTr.github.io/tree/hexo-content

具体情况是这样，如果不使用next主题，主页(index)生成的文章会包含”冲绳“旅行的这篇文章。但是，使用了next，主页就没有这篇文章了，第二页也没有（我一共两页主页），就是说，在主页中无法找到这篇文章。但是可以在archeive里面找到，点击链接也能进入。我现在已经部署出去的网站就是有问题，可以参考这里 [winterTTr.me](http://winterTTr.me)。主页的所有文章中都不包含”三年签证之冲绳两日游“，但是在archieves里面可以找到。

我本地用hexo s预览的话，表现是这样的：如果只是hexo server的话，是可以看到文章的，但是hexo server -s的话（即不使用动态编译，只是使用public文件夹的内容预览），就是缺少刚刚提到的文章。但是部署本身会使用public中的静态文件，所以我部署出去的网站就有问题了。

我本地已经尝试hexo clean && hexo generate重新生成所有的，也不能解决问题。

所以，我想问一下iissnan是否有可能是next的问题，或者是我的某些配置引起的？
至少我现在如果不使用next，就不会出现刚刚说的问题。

**Comment by kisnows** [comment]
我也遇到了这个问题，貌似是在时间跨年的时候会有。
![2016-01-12_215623](https://cloud.githubusercontent.com/assets/9394000/12265314/61b8d0a2-b977-11e5-9c7e-b07a586796f7.png)
下面是主题的配置文件，
```yml
# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Place your favicon.ico to /source directory.
favicon: /favicon.ico

# Set default keywords (Use a comma to separate)
keywords: "JavaScript,JS,Web Develop,Front end,前端开发,Kisnows"

# Set rss to false to disable feed link.
# Leave rss as empty to use site's feed link.
# Set rss to specific value if you have burned your feed already.
rss:

# Specify the date when the site was setup
since: 2014




# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

# When running hexo in a subdirectory (e.g. domain.tld/blog)
# Remove leading slashes ( "/archives" -> "archives" )
menu:
  home: /
  categories: /categories
  #about: /about
  archives: /archives
  tags: /tags
  #commonweal: /404.html


# Enable/Disable menu icons.
# Icon Mapping:
#   Map a menu item to a specific FontAwesome icon name.
#   Key is the name of menu item and value is the name of FontAwsome icon.
#   When an question mask icon presenting up means that the item has no mapping icon.
menu_icons:
  enable: true
  # Icon Mapping.
  home: home
  about: user
  categories: th
  tags: tags
  archives: archive
  commonweal: heartbeat




# ---------------------------------------------------------------
# Scheme Settings
# ---------------------------------------------------------------

# Schemes
#scheme: Muse
#scheme: Mist
scheme: Pisces



# ---------------------------------------------------------------
# Sidebar Settings
# ---------------------------------------------------------------


# Social links
# social:
  #GitHub:
  #Others:

# Social Icons
social_icons:
  enable: true
  # Icon Mappings
  GitHub: github
  Twitter: twitter
  Weibo: weibo


# Sidebar Avatar
avatar: '/imgs/avatar.jpg'


# TOC in the Sidebar
toc:
  enable: true

  # Automatically add list number to toc.
  number: true


# Creative Commons 4.0 International License.
# http://creativecommons.org/
# Available: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
creative_commons: by-nc-sa
#creative_commons:

sidebar:
  # Sidebar Position, available value: left | right
  position: left
  #position: right

  # Sidebar Display, available value:
  #  - post    expand on posts automatically. Default.
  #  - always  expand for all pages automatically
  #  - hide    expand only when click on the sidebar toggle icon.
  #  - remove  Totally remove sidebar including sidebar toggle icon.
  display: post
  #display: always
  #display: hide
  #display: remove



# ---------------------------------------------------------------
# Misc Theme Settings
# ---------------------------------------------------------------

# Custom Logo.
# !!Only available for Default Scheme currently.
# Options:
#   enabled: [true/false] - Replace with specific image
#   image: url-of-image   - Images's url
custom_logo:
  enabled: false
  image:


# Code Highlight theme
# Available value:
#    normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: normal

# Automatically scroll page to section which is under <!-- more --> mark.
scroll_to_more: true

# Automatically Excerpt
auto_excerpt:
  enable: false
  length: 150

# Use Lato font
use_font_lato: true



# ---------------------------------------------------------------
# Third Party Services Settings
# ---------------------------------------------------------------

# MathJax Support
mathjax:


# Swiftype Search API Key
#swiftype_key:

# Baidu Analytics ID
#baidu_analytics:

# Duoshuo ShortName
#duoshuo_shortname:

# Disqus
#disqus_shortname:

# Share
#jiathis:

# Share
#duoshuo_share: true

# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
#google_site_verification:


# Google Analytics
#google_analytics:


# Make duoshuo show UA
# user_id must NOT be null when admin_enable is true!
# you can visit http://dev.duoshuo.com get duoshuo user id.
duoshuo_info:
  ua_enable: false
  admin_enable: false
  user_id: 0
  #admin_nickname: ROOT


# Facebook SDK Support.
# https://github.com/iissnan/hexo-theme-next/pull/410
facebook_sdk:
  enable: false
  app_id:       #<app_id>
  fb_admin:     #<user_id>
  like_button:  #true
  webmaster:    #true


# Show number of visitors to each article.
# You can visit https://leancloud.cn get AppID and AppKey.
leancloud_visitors:
  enable: true
  app_id: ************
  app_key: **********


#! ---------------------------------------------------------------
#! DO NOT EDIT THE FOLLOWING SETTINGS
#! UNLESS YOU KNOW WHAT YOU ARE DOING
#! ---------------------------------------------------------------

# Motion
use_motion: false

# Fancybox
fancybox: false

# Static files
vendors: vendors
css: css
js: js
images: images

# Theme version
version: 5.0.0

```
