### ISSUE TITLE
使用OSS+CDN部署网站默认地址不显示index.html

### ISSUE THREAD

**Issue by shishuo365** [iissnan/hexo-theme-next#604]
使用OSS+CDN部署网站，CND通常不支持默认目录指向 index.html，这种情况下，分类，标签页显示都会指向到首页；

要如何修改才能让所有地址的显示中都不省略掉 index.html

**Comment by iissnan** [comment]
在你所设定的前提下，首先是 `permalink` 要加上 `index.html`。例如：

```yml
permalink: :year/:title/index.html
```

另外一个是 菜单部分，同样也需要明确指定到 `index.html`。例如：

```yml
menu:
  home: /index.html
  archives: /archives/index.html
  tags: /tags/index.html
```

另外一个是分页导航，这里需要更改模板（`layout/_partials/pagination.swig`），分页辅助函数传递 `format` 选项：

```
paginator({
        prev_text: '<i class="fa fa-angle-left"></i>',
        next_text: '<i class="fa fa-angle-right"></i>',
        mid_size: 1,
        format: 'page/%d/index.html`
      })
```
