### ISSUE TITLE
如何彻底隐藏侧边栏

### ISSUE THREAD

**Issue by Titzanyic** [iissnan/hexo-theme-next#624]
想去修改一下源码，但是尝试了一下，没有找到。请问各位如何去掉底部展开侧边栏的按钮。

**Comment by zoakerc** [comment]
在文件 `source/css/_custom/custom.styl` 中，加入CSS控制其不显示即可。
```css
.sidebar-toggle {
    display: none;
}
```
