### ISSUE TITLE
侧边栏不显示，sidebar: post会出错

### ISSUE THREAD

**Issue by skycrown** [iissnan/hexo-theme-next#625]
添加sidebar: post，之后，使用hexo g，会出错，其中d:\blog是我的博客根目录
Unhandled rejection Error: ENOENT: no such file or directory, open 'd:\blog\themes\next\layout\_scripts\schemes\.swig'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)

**Comment by skycrown** [comment]
好像把position: left和display: post去掉就可以了

**Comment by cinthisime** [comment]
```
npm install async
```

**Comment by skycrown** [comment]
谢谢cinthisime，按你说的方法，解决了！

**Comment by ningwy** [comment]
我也遇到同样的问题，但是按照cinthisime所说的方法不行/(ㄒoㄒ)/~~

**Comment by skycrown** [comment]
我的配置：
```
sidebar:
  # Sidebar Position, available value: left | right
  #position: left
  position: right

  # Sidebar Display, available value:
  #  - post    expand on posts automatically. Default.
  #  - always  expand for all pages automatically
  #  - hide    expand only when click on the sidebar toggle icon.
  #  - remove  Totally remove sidebar including sidebar toggle icon.
  display: post
  #display: always
  #display: hide
  #display: remove
```
你的会报错吗，我用的Pisces这个主题
