### ISSUE TITLE
Host in subdirectory 子目錄架站

### ISSUE THREAD

**Issue by goodseller** [iissnan/hexo-theme-next#64]
你好, 這個模版很棒, 

我想在自己的Github 的子目錄上架站 
http://goodseller.github.io/blog/

在 _config.yml裡加入了

    url: http://goodseller.github.io/blog
    root: /blog/

圖片可以顯示, 只是 
 
首页 归档 标签 的 連結還指著根目錄

我也試過, 
改 _config.yml

    # Directory
    source_dir: source
    public_dir: public
    tag_dir: tags
    archive_dir: archives
    category_dir: categories
    code_dir: downloads/code
    i18n_dir: :lang
    skip_render:

只是還是不行, 他會在hexo generate 的時候也建了在子目錄, 
可以幫我看一下/ 加入:root 到連結中嗎?

謝謝

**Comment by iissnan** [comment]
在主题的 `_config.yml` 中，将菜单配置前面的 `/` 去掉就可以。例如：

```
menu:
  home: /
  categories: categories
  archives: archives
  tags: tags
```
