### ISSUE TITLE
请问怎样在sidebar添加邮箱？

### ISSUE THREAD

**Issue by crazy-canux** [iissnan/hexo-theme-next#745]
请问怎样在sidebar添加邮箱？

**Comment by iissnan** [comment]
```yml
# Social links
social:
  email: mailto:your email address

social_icons:
  enable: true
  email: envelope
```

http://theme-next.iissnan.com/theme-settings.html#author-sites
