### ISSUE TITLE
代码段显示BUG

### ISSUE THREAD

**Issue by 2b2b2b2b** [iissnan/hexo-theme-next#749]
![image](https://cloud.githubusercontent.com/assets/16076364/13990320/e116ffea-f14e-11e5-8674-96f5bc5ea8fc.png)
代码段 前面空白段BUG

代码高亮设置也无效···

**Comment by iissnan** [comment]
方便将这篇文档以及站点的 `_config.yml` 中以下 highlight 那段配置发一下吗：

```
highlight:
  enable: true
  auto_detect: true
  line_number: true
  tab_replace:
```
