### ISSUE TITLE
MathJax CDN修改

### ISSUE THREAD

**Issue by wylhyz** [iissnan/hexo-theme-next#752]
这个主题的MathJax在中文语言下使用的mathjax版本比较老，我今天用的时候发现在chrome下测试出现在mathjax的公式后面出现了一条竖线。
我因此将mathjax的CDN从staticFILE修改成了bootCDN提供的文件，作者看看是不是能改一下。

**Comment by iissnan** [comment]
多谢反馈。我看了下 MathJax 官网也有提供一个 CDN 版本，我在想干脆增加一个配置 cdn 的选项，可以自己配置需要使用的 cdn，默认官方提供的 版本：

```yml
mathjax:
  enable: true
  cdn: https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
```

你自己可以先那么改，这个预计会在下一个版本里（5.0.1）
