### ISSUE TITLE
感觉浏览器留白太多，代码块看起来比较麻烦

### ISSUE THREAD

**Issue by HanderWei** [iissnan/hexo-theme-next#759]
因为大部分用户还是写技术文档，代码块使用的比例还是很高的，如果经常需要拖动查看代码，体验非常差。

如果我重置了Post的宽度，侧边栏就会显示不完整。

请问有什么方法可以解决吗？

thx

**Comment by ledisthebest** [comment]
什么意思？

**Comment by HanderWei** [comment]
@ledisthebest 
就是说，页面两侧的空白太多，导致文章的宽度比较窄，一行代码如果显示不完整的话，就需要左右拖动才能查看整行代码，对于代码比较多的文章看起来就会比较累。

就像这样：
![2016-03-27 10 09 22](https://cloud.githubusercontent.com/assets/5194035/14063441/05245984-f404-11e5-8999-1e54a4fd8bcf.png)

**Comment by iissnan** [comment]
试试增加 `content-wrap` 的宽度：http://theme-next.iissnan.com/faqs.html#custom-content-width

**Comment by HanderWei** [comment]
@iissnan 我试了增加 content-desktop 的值，这样会覆盖侧边栏


如何设置覆盖浏览器宽度？我觉得这样阅读体验会好一些

**Comment by iissnan** [comment]
对于 Pisces Scheme，需要同时修改 `header` 的宽度、`.main-inner` 的宽度以及 `.content-wrap` 的宽度。例如，使用百分比（Pisces 的布局定义在 `source/css/_schemes/Picses/_layout.styl` 中）：

```css
header{ width: 90%; }
.container .main-inner { width: 90%; }
.content-wrap { width: calc(100% - 260px); }
```

我并未对这个布局进行测试，自定义修改需要自己进行测试。另外，我觉得超过一定宽度后（一行内文字太多导致换行跨度太大），阅读体验都不怎么样。

**Comment by HanderWei** [comment]
@iissnan 确实如此，需要在代码行和文字内容之间取个平衡

**Comment by HanderWei** [comment]
谢谢 @iissnan ，亲测有效

**Comment by imwillxue** [comment]
感谢

**Comment by ethan-funny** [comment]
感谢，我要遇到这个问题。

**Comment by renzhaozhao** [comment]
我发现修改样式后本地有效果，部署上去就没效果了，这是为啥呢

**Comment by liuli1735** [comment]
@iissnan 建议这块做到自适应好些吧

**Comment by Hclmaster** [comment]
@renzhaozhao 你可以先进行hexo clean一下，我也是遇到你这个问题了，然后我clean了一下就好了。

**Comment by raykle** [comment]
请问一下，我现在按照上面的代码修改了使用百分比来显示宽度。但是这种情况下屏幕较小的话，width 会比较小体验不好，如果我想在百分比的前提下，让 width 有一个最小 960px 的宽度，要怎么设置呢？
谢谢~ 😄

**Comment by iTofu** [comment]
感谢 @iissnan 的方法，很有效！确实纠结代码阅读有段时间了！

建议使用 80%，阅读代码完全 ok，正常段落也不会留白太多，阅读体验更好！

````css
header{ width: 80%; } /* 80% */
.container .main-inner { width: 80%; } /* 80% */
.content-wrap { width: calc(100% - 260px); }
````

**Comment by Zeecoders** [comment]
感谢@iTofu，按照你的比例来设之后，确实效果好了很多！！！！

**Comment by xiaoli123** [comment]
修正下楼上少了个点‘.’，且要放到最下面
.header{ width: 80%; } /* 80% */
.container .main-inner { width: 80%; } /* 80% */
.content-wrap { width: calc(100% - 260px); }

**Comment by songyibin** [comment]
这样设置在桌面端可以，但是在移动端不适应啊，要怎么修改？ @iissnan

**Comment by hhysj** [comment]
把字体改小一点,比如12, 代码看起来更好.

**Comment by aidansu** [comment]
.header{ 
  width: 80%;
  +tablet() {
    width: 100%;
  } 
  +mobile() {
    width: 100%;
  }
}
.container .main-inner { 
  width: 80%;
  +tablet() {
    width: 100%;
  } 
  +mobile() {
    width: 100%;
  }
}
.content-wrap { 
  width: calc(100% - 260px); 
  +tablet() {
    width: 100%;
  }
  +mobile() {
    width: 100%;
  }
}

**Comment by aidansu** [comment]
``` css
.header{
    width: 80%;
    +tablet() {
        width: 100%;
    }
    +mobile() {
        width: 100%;
    }
}

.container .main-inner {
    width: 80%;
    +tablet() {
        width: 100%;
    }
    +mobile() {
        width: 100%;
    }
}

.content-wrap {
    width: calc(100% - 260px);
    +tablet() {
        width: 100%;
    }
    +mobile() {
        width: 100%;
    }
}
```

**Comment by xiao-fang** [comment]
楼主推荐的这种方式在桌面端没问题, 但是在手机平板等响应式布局会有问题.
```css
.header{ width: 80%; } /* 80% */
.container .main-inner { width: 80%; } /* 80% */
.content-wrap { width: calc(100% - 260px); }
```
我尝试了以下修改: 
[next/source/css/_schemes/Pisces/_layout.styl](https://github.com/xiao-fang.github.io/themes/next/source/css/_schemes/Pisces/_layout.styl)
预览:http://xiao-fang.me/ 可以解决这个问题.
