### ISSUE TITLE
[Future]支持快速切换CDN加载js库

### ISSUE THREAD

**Issue by myoss** [iissnan/hexo-theme-next#783]
### Expected behavior (预期行为)
支持`CDN`加速`js`库，这是我自己改动后的效果
![qq 20160402091445](https://cloud.githubusercontent.com/assets/6986459/14223635/8c7626a6-f8b4-11e5-9fcb-58ae6ee28e78.png)
![qq 20160402092654](https://cloud.githubusercontent.com/assets/6986459/14223656/10f87500-f8b5-11e5-91b1-070aa5c61265.png)

### Actual behavior (实际行为)
现在`source\vendors`目录下`js`库存放的路径不能快速的切换到`CDN`

### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master  ✔ 
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces  ✔ 

### Other Informations (Like Browser, System, Screenshots)
 - chrome 49
 - windows 10

**Comment by iissnan** [comment]
想法不错。

不过要进行切换的前提是 cdn 之间包的存储是否采用相同的路径，我感觉这个不能受保证。

**Comment by myoss** [comment]
现在大部分的`CDN`厂商提供的加速服务，在路径上都是一致的，除了少部分（比如：新浪）提供的特殊，所以是可以考虑这么做的，既然都能支持大部分的厂商了，总比没有的好吧，希望你能考虑一下吧，对于整个项目来说实施起来也不是非常困难的事情。

这是我之前收集到的一些`CDN`厂商（地址：[常用的-JavaScript-库-CDN-加速服务](http://myoss.github.io/2016/%E5%B8%B8%E7%94%A8%E7%9A%84-JavaScript-%E5%BA%93-CDN-%E5%8A%A0%E9%80%9F%E6%9C%8D%E5%8A%A1/)），或者`Google`

1.  https://developers.google.com/speed/libraries/#jquery

    ```
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
    ```

2. http://libs.useso.com/

    ```
    http://libs.useso.com/js/jquery/2.0.3/jquery.js
    ```

3. http://developer.baidu.com/wiki/index.php?title=docs/cplat/libs#jQuery

    ```
    <script src="http://libs.baidu.com/jquery/2.0.0/jquery.js"></script>
    <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
    ```

4. http://www.bootcdn.cn/jquery/

    ```
    //cdn.bootcss.com/jquery/2.2.1/jquery.js
    ```

**Comment by myoss** [comment]
#629 这个功能非常棒，这两天更新用上了非常不错，感谢作者~~~

**Comment by mritd** [comment]
我想知道 我有自己的 cdn  怎么破？？？  upyun  七牛 都有

**Comment by panzhitian** [comment]
为什么不把jquery.fancybox.css和font-awesome也加进去呢？

**Comment by iissnan** [comment]
jquery.fancybox.css 应该是要开放出去，避免版本不一致的问题。

FontAwesome 我还没想好怎么处理。

**Comment by mritd** [comment]
今天测试了一下。。。因为这几个 JS。。。加载硬是拖到 40S。。。  能否提供个 自定义 这几个 js 路径的功能？  我所有图片全部放在 upyun上。。。如果可以我想自己把这几个 js 拿下来放到自己的 cdn 上。

**Comment by panzhitian** [comment]
自己硬改是可以的。我猜作者应该在考虑fallback的处理。

**Comment by urzone** [comment]
头疼的FontAwesome啊，直接加载了22s 出去了。。。。
![screen shot 2016-04-25 at 00 28 19](https://cloud.githubusercontent.com/assets/11997420/14768740/bbbb50d8-0a7c-11e6-8737-5e74b62f587f.png)

**Comment by iissnan** [comment]
@panzhitian jquery.fancybox.css 和 font-awesome 都可以设置 CDN 地址。
@mritd 可以自定义资源的路径，例如：

```yml
vendors:
  # Internal path prefix. Please do not edit it.
  _internal: vendors

  # Internal version: 2.1.3
  jquery: //cdn.jsdelivr.net/jquery/2.1.3/jquery.min.js

  # Internal version: 2.1.5
  # Fancybox: http://fancyapps.com/fancybox/
  fancybox: //cdn.jsdelivr.net/fancybox/2.1.5/jquery.fancybox.pack.js
  fancybox_css: //cdn.jsdelivr.net/fancybox/2.1.5/jquery.fancybox.min.css

  # Internal version: 1.0.6
  fastclick: //cdn.jsdelivr.net/fastclick/1.0.6/fastclick.min.js

  # Internal version: 1.9.7
  lazyload: //cdn.jsdelivr.net/jquery.lazyload/1.9.3/jquery.lazyload.min.js

  # Internal version: 1.2.1
  velocity: //cdn.jsdelivr.net/velocity/1.2.3/velocity.min.js

  # Internal version: 1.2.1
  velocity_ui: //cdn.jsdelivr.net/velocity/1.2.3/velocity.ui.min.js

  # Internal version: 0.7.9
  ua_parser: //cdn.jsdelivr.net/ua-parser.js/0.7.10/ua-parser.min.js

  # Internal version: 4.4.0
  # http://fontawesome.io/
  fontawesome: //maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css
```
