### ISSUE TITLE
建议将字体等带google的替换成中科大的库

### ISSUE THREAD

**Issue by njzhenghao** [iissnan/hexo-theme-next#806]
因为中科大的库是完全镜像，速度很快，并且支持https

**Comment by iissnan** [comment]
试试 v5.0.1 分支，在那个分支上可以自定义字体使用的 cdn 源。例如我现在使用的配置：

```yml
# ---------------------------------------------------------------
# Font Settings
# - All fonts set here will have the following styles:
#     light, light italic, normal, normal intalic, bold, bold italic
# - Be aware that setting too much fonts will cause site running slowly
# - Introduce in 5.0.1
# ---------------------------------------------------------------
font:
  enable: true

  # Uri of fonts host. E.g. //fonts.googleapis.com (Default)
  host:

  # Global font settings used on <body> element.
  global:
    # external: true will load this font family from host.
    external: true
    family: Monda

  # Font settings for Headlines (h1, h2, h3, h4, h5, h6)
  # Fallback to `global` font settings.
  heading:
    external: true
    family:

  # Font settings for posts
  # Fallback to `global` font settings.
  post:
    external: true
    family:

  # Font settings for Logo
  # Fallback to `global` font settings.
  logo:
    external: true
    family: Lobster Two
    size: 24

  # Font settings for <code> and code blocks.
  code:
    external: true
    family: PT Mono
```
