### ISSUE TITLE
更灵活的侧边栏显示

### ISSUE THREAD

**Issue by seanlook** [iissnan/hexo-theme-next#825]
现在侧边栏显示默认是 post ，即只有在文章详情页才主动显示。不知是否只我一个人希望在主页也显示侧边栏，但 always 会把tags，archives等页也显示出sidebar，有点别扭。

所以如果增加 indexpost 之类的选项，只在index和post页面主动显示侧边栏就好了。

**Comment by Haocen** [comment]
没懂？你需要的是显示目录，同时不要显示标签和存档数量？
烦请按格式报告问题，并附带截图。

**Comment by iissnan** [comment]
主页都显示了，为啥 tags 和 archives 页面不显示，感觉更别扭 : sweat_smile:

**Comment by ivan-nginx** [comment]
@seanlook dont understand u, write in English if not solved. If solved, close it please.

**Comment by seanlook** [comment]
I mean more flexible sidebar settings. For example, I need sidebar just shows up in *index* page by default and *post* page shall be clean. Also *tags* and `archives` pages.

You don't have to do this :)

**Comment by ivan-nginx** [comment]
@seanlook alright, let's see options in `_config.yml` :
```
# Table Of Contents in the Sidebar
toc:
  enable: true
...
sidebar:
  # Sidebar Position, available value: left | right
  position: left
  #position: right

  # Sidebar Display, available value:
  #  - post    expand on posts automatically. Default.
  #  - always  expand for all pages automatically
  #  - hide    expand only when click on the sidebar toggle icon.
  #  - remove  Totally remove sidebar including sidebar toggle.
  display: post
  #display: always
  #display: hide
  #display: remove
```
For now sidebar show everywhere and if u don't want display only `TOC`, u may change `toc` to `false`. Sidebar (with avatar, etc.) will be displayed everywhere.
