### ISSUE TITLE
自定义字体设置 typo

### ISSUE THREAD

**Issue by billjh** [iissnan/hexo-theme-next#856]
### Expected behavior (预期行为)

在 _config.yml 配置文件中可以自定义 heading 和 post 的字体。如：

```
font:
  enable: true

  # Uri of fonts host. E.g. //fonts.googleapis.com (Default)
  host:

  # Global font settings used on <body> element.
  global:
    # external: true will load this font family from host.
    external: true
    family: Lato

  # Font settings for Headlines (h1, h2, h3, h4, h5, h6)
  # Fallback to `global` font settings.
  headings:
    external: true
    family: Open Sans

  # Font settings for posts
  # Fallback to `global` font settings.
  posts:
    external: true
    family: Roboto

```

### Actual behavior (实际行为)

不能生效因为 headings 关键字和 external-fonts.swig 模板中的 font_config.heading 不对应，不能被识别。同样的还有 posts 关键字。

### 解决方案

改为

```
  heading: # 原来为 headings
    external: true
    family: Open Sans

  post: # 原来为 posts
    external: true
    family: Roboto
```
