### ISSUE TITLE
怎么把侧边栏的文章目录改成无序列表表示。

### ISSUE THREAD

**Issue by DVD0423** [iissnan/hexo-theme-next#857]
写文章的时候，习惯在正文段落中加个序号。这样就导致了侧边栏文章目录显示出现重复序号问题，具体如下：

> 1. 1 跟踪系统调用
> 2. 2 系统调用分析
> 3. 3 添加系统调用

所以，怎么把侧边栏的自动序号消去？

**Comment by forrestchang** [comment]
编辑主题下的 `_config.yml` 文件，

``` yaml
# TOC in the Sidebar
toc:
  enable: true

  # Automatically add list number to toc.
  number: true
```

把 `number` 的 `true` 改成 `false`。
