### ISSUE TITLE
怎么给侧边栏的社交链接设置图标

### ISSUE THREAD

**Issue by FourEyebrowXiake** [iissnan/hexo-theme-next#904]

**Comment by jerrybendy** [comment]
```yml
social_icons:
  enable: true
  GitHub: github
  Twitter: twitter
  Weibo: weibo
  Coding: heart
```

冒号左边的名字可以自己定义，但要和`social`中的相同，图标使用 font-awasome 中的图标
