### ISSUE TITLE
内容页内的图片居中问题

### ISSUE THREAD

**Issue by xovel** [iissnan/hexo-theme-next#910]
希望能够有这样的效果，可以让文章中的图片处于居中状态。

~~默认调用的fancybox并没有给图片一个居中的样式，只给了**图片标题（img-caption）居中**。~~

已经解决。

在全局样式中有
```css  
.post-body img { margin: 0; }
```
> \source\css\_schemes\Mist\_posts-expanded.styl - Line 30
这样的代码，解析出来之后是这个样子的：

```css
.posts-expand .post-body img {
  margin: 0;
}
```

fancybox中指定的样式代码：
```css
.post-body .fancybox img {
  display: block !important;
  margin: 0 auto;
  cursor: pointer;
  cursor: zoom-in;
  cursor: -webkit-zoom-in;
}
```
>  \source\css\_common\components\post\post.styl - Line 7~13

解析出来之后是这样的：
```css
.post-body .fancybox img {
  display: block !important;
  margin: 0 auto;
  cursor: pointer;
  cursor: zoom-in;
  cursor: -webkit-zoom-in;
}
```

这两段代码的css权重是一样的，于是就取决于具体css代码的顺序了。hexo生成css时fancy相关的代码在前面，于是就被后面的posts-expand给覆盖了。

修改以上代码：
```css
.post-body .fancybox img {
  display: block !important;
  margin: 0 auto !important;
  cursor: pointer;
  cursor: zoom-in;
  cursor: -webkit-zoom-in;
}
```

使用important强制居中对齐即可。
