### ISSUE TITLE
两个显示的小问题

### ISSUE THREAD

**Issue by hunao0221** [iissnan/hexo-theme-next#922]
1. 这里重复了，下方带图标的是无法点击的
   ![image](https://cloud.githubusercontent.com/assets/11972530/15678081/74c8852c-277f-11e6-974f-5392a71b3a99.png)
2. 打赏没有图标
   ![image](https://cloud.githubusercontent.com/assets/11972530/15678094/8b5becfc-277f-11e6-90e6-b44488abc74c.png)

**Comment by djyde** [comment]
可以提供一下 _config.yml 里 social 相关的配置吗？

**Comment by hunao0221** [comment]
@djyde 已发你邮箱

**Comment by djyde** [comment]
我贴上来吧，这样别人也能帮到你

```yml
# Social Links
# Key is the link label showing to end users.
# Value is the target link (E.g. GitHub: https://github.com/iissnan)
social:
  #LinkLabel: Link
  GitHub: https://github.com/hunao0221
  Google: https://plus.google.com/u/0/+%E8%83%A1%E9%97%B9


# Social Links Icons
# Icon Mapping:
#   Map a menu item to a specific FontAwesome icon name.
#   Key is the name of the item and value is the name of FontAwsome icon. Key is case-senstive.
#   When an globe mask icon presenting up means that the item has no mapping icon.
social_icons:
  enable: true
  # Icon Mappings.
  # KeyMapsToSocalItemKey: NameOfTheIconFromFontAwesome
  GitHub: github
  Twitter: twitter
  Weibo: weibo
  Google: google-plus
```
