### ISSUE TITLE
about页面的无序列表的样式没有小圆圈

### ISSUE THREAD

**Issue by isunimp** [iissnan/hexo-theme-next#934]
### Expected behavior (预期行为)

列表前面应该是有小圆圆的
### Actual behavior (实际行为)

没有小圆圈
### NexT Informations

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  [x] Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  [x] Mist
  -  Pisces

**Comment by lengthmin** [comment]
我也

**Comment by isunimp** [comment]
@lengthmin 你解决了么？
我在 about/index.html 文件中加如下代码，暂时解决了
```css
<style type="text/css">
ul {
  list-style-type: disc;
}
</style>
```
