### ISSUE TITLE
如何修改NexT主题Markdown分割线渲染效果？

### ISSUE THREAD

**Issue by jwwangchn** [iissnan/hexo-theme-next#942]
个人感觉NexT主题Markdown**分割线**渲染结果不是很好看，想请教一下，如何修改Markdown渲染方式？

**Comment by xovel** [comment]
是`hr`的样式么？搜一下styl文件就知道了。

`\source\css\_common\scaffolding\base.styl`
在Line71处。
```css
hr {
  margin: 40px 0;
  height: 3px;
  border: none;
  background-color: $gray-lighter;
  background-image: repeating-linear-gradient(
    -45deg,
    white,
    white 4px,
    transparent 4px,
    transparent 8px
  );
}
```

部分样式~~可能~~在其他文件中有覆盖：
`\source\css\_schemes\Mist\_base.styl`
在Line9处。
```css
hr {
  margin: 20px 0;
  height: 2px;
}
```
