### ISSUE TITLE
顶端目录加入自定义页面

### ISSUE THREAD

**Issue by rickyking** [iissnan/hexo-theme-next#95]
请问目前可以在上方目录里可以加入自定义的页面(page)吗？

目前仅有“关于”页面，可以开放自定义其他页面吗？

谢谢作者的精心设计！！

**Comment by iissnan** [comment]
是指在菜单中加入页面的链接吗？

假设新建的页面名称是 `foo` (`hexo new page foo`)，编辑主题的 `_config.yml`，在 `menu` 下加入一行即可：

```yml
menu:
  foo: /foo
```

**Comment by rickyking** [comment]
修改成：
menu:
  test: /test
![imq9s7hb6zrmjf6eweq600tjt-n97oi4t3bx5mruu4g](https://cloud.githubusercontent.com/assets/2820809/7095730/f9dc7580-dfcc-11e4-88ee-acf13130563a.png)

**Comment by iissnan** [comment]
我也遗漏了一步，:smile:

Menu 有做多语言支持，所以需要在 `languages` 目录下语言中加上对应的翻译：

```
menu:
  home: Home
  archives: Archives
  categories: Categories
  tags: Tags
  about: About
  test: test
```
