### ISSUE TITLE
Mist主题如何使图片去除灰色边框

### ISSUE THREAD

**Issue by Nirvanada** [iissnan/hexo-theme-next#963]
插入图片后图片会存在灰色边框，看到/source/css/_variables/base.styl中可以将table的边框去除，但不知道对于图片如何处理

**Comment by xovel** [comment]
`..\source\css\_common\components\post\post-expand.styl` Line 48
```css
  img {
    box-sizing: border-box;
    margin: auto;
    padding: 3px;
    border: 1px solid $gray-lighter;
  }
```
