### ISSUE TITLE
设置highlight_theme后代码还是无法高亮

### ISSUE THREAD

**Issue by gydmercy** [iissnan/hexo-theme-next#989]
我在 next 配置文件中更改 highlight_theme 的值比如 normal 或者 night。代码部分的底色确实会改变，但是代码本身没有一点高亮，这是为什么呢？以前是好的，我后来迁移了电脑，更新了 next 主题后，就这样了。当前使用版本5.0.1

**Comment by shaohui10086** [comment]
应该是你没设置代码的语言
simple：``` java      ```
在```后面跟上语言

**Comment by gydmercy** [comment]
以前不设置代码语言也可以高亮

**Comment by TanJunDang** [comment]
在哪里设置simple啊  主题下的yml？

**Comment by AirmaZ** [comment]
同问，我现在也是这个问题，lz解决了吗

**Comment by gydmercy** [comment]
算是找到个折中的办法吧

在markdown中，代码块用 '''  '''包裹就可以高亮，直接行首加 tab 来包裹代码块就无法高亮

以前两者都可以高亮的

**Comment by AirmaZ** [comment]
@gydmercy 
多谢，next的代码高亮真实迷啊

**Comment by iissnan** [comment]
@gydmercy 可能是你升级了 Hexo。Hexo 新版本里代码高亮默认是不做自动检测，从而导致失效。解决方法是修改你的站点配置文件，将 `hilight.auto_detect` 设置为 `true`：

```yml
highlight:
  enable: true
  auto_detect: true
  line_number: true
  tab_replace:
```

**Comment by gydmercy** [comment]
确实是之前是好的，我换了电脑装了最新版 hexo 后 代码就不高亮了。
不过我看了下站点配置文件，你所说的那个地方本来就是 true 。但还是没什么作用。

2016年10月19日星期三，Vi <notifications@github.com> 写道：

**Comment by otherfish** [comment]
确实是，我的主题版本是: 

Theme version：version: 0.4.5.1

无论是在代码段加上四个空格还是用 <code>```bash</code> 语法都是显示的黑底白字

![snipaste20161028_124055](https://cloud.githubusercontent.com/assets/12808134/19795156/d4599af6-9d0b-11e6-8aef-7a12085c02ee.png)

例如:
![snipaste20161028_124241](https://cloud.githubusercontent.com/assets/12808134/19795180/0d4498b6-9d0c-11e6-877d-fb42440bfad5.png)

**Comment by lixiansky** [comment]
这个问题是 设置 Social Links Icon 导致的！！！你把
```
social:
  GitHub: https://github.com/lixiansky
  Twitter: https://twitter.com/lixiansky
  Weibo: http://weibo.com/2275360065/
```
配置放到你的站点配置信息里，不要放在主题配置信息里，就可以了！！！
**PS：**这个问题还导致“打赏”功能的样式，全部丢失！！！！我查看了一下main.css少几百行代码，具体的源码没有看！！

**Comment by bigggge** [comment]
同，四个空格的代码块不能高亮，怎么解决

**Comment by seanhuang514** [comment]
我也有一樣的問題，highlight有設true了， ```ruby 後面也加上語言了，但還是如下面的圖一樣沒有highlight，請問有人有解嗎？
```
highlight:
  enable: true
  auto_detect: true
  line_number: true
  tab_replace:
```
<img width="703" alt="2017-03-21 10 43 36" src="https://cloud.githubusercontent.com/assets/22285238/24152882/df867d66-0e87-11e7-9d90-44451e15b56b.png">
